/**
 * Smoke test for the `app:` recorder target. Not a published video: it proves
 * record.mjs can scaffold a real Studio app, install it, boot its dev server
 * and record against it. Run with TTS_PROVIDER=silence so it costs no quota.
 *
 *   TTS_PROVIDER=silence node tools/tutorials/record.mjs app-smoke --serve
 */
export default {
  id: 'app-smoke',
  kind: 'marketing',
  // Keeps the run out of the published manifest: this is a pipeline test, so it
  // has no title card, no end card and no narration worth 15 seconds, and every
  // manifest guardrail it trips is a false alarm about a video nobody ships.
  internal: true,
  title: 'app target smoke test',
  description: 'Internal: proves the recorder can scaffold, install, serve and record a real SvelteKit app generated by Studio.',
  tags: ['internal'],
  view: { width: 1920, height: 1080 },
  // How to build the app this script records. One per run.
  appScaffold: { studio: 'customers-orders' },

  segments: [
    {
      app: '/customers',
      introHold: 0.4,
      async setup(page, h) {
        await h.pause(2500)
      },
      beats: [
        {
          say: 'A real SvelteKit app, scaffolded from a dataset and running on its own dev server.',
          lead: 300,
          async do(page, h) {
            // The generated customers screen renders a grid. If the app booted
            // but the page is blank, that is the failure worth catching.
            await page.waitForSelector('.sv-grid-body [role="row"], table tbody tr', { timeout: 30_000 })
            const rows = await page.locator('.sv-grid-body [role="row"], table tbody tr').count()
            if (rows < 1) throw new Error(`the generated customers page rendered ${rows} rows`)
            h.log(`generated app rendered ${rows} rows`)
            await h.pause(1500)
          },
          hold: 400,
        },
      ],
    },
  ],
}
