/**
 * Split the MCP manifest into what the Worker bundles and what it fetches.
 *
 * A Worker has a hard bundle limit and a startup CPU budget, and the full
 * manifest is ~6 MB of JavaScript object literal - parsing that on every cold
 * start would blow the budget on its own. So:
 *
 *   bundled  (src/generated/index.ts)  listings + the API surface. Small, and
 *            needed by tools/list and by every check_svgrid_code call.
 *   assets   (public/_data/**)         doc bodies and demo sources. Fetched
 *            through the ASSETS binding on first use and cached in module
 *            scope for the life of the isolate.
 *
 * Run from this directory: `node scripts/build-data.mjs`
 * (`pnpm build:data`, which the deploy script runs first).
 */
import { mkdirSync, writeFileSync, rmSync, copyFileSync, existsSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const root = join(here, '..')
const repoRoot = join(root, '..', '..')
const mcpDist = join(repoRoot, 'packages', 'mcp', 'dist')

if (!existsSync(join(mcpDist, 'data.js'))) {
  console.error('build-data: packages/mcp is not built. Run `pnpm --filter @svgrid/mcp build` first.')
  process.exit(1)
}

const { examples, docs, apiReference, apiSurface } = await import(
  pathToFileURL(join(mcpDist, 'data.js')).href
)

/** Trim a demo blurb to one line for the listing. */
function trimBlurb(text, max = 120) {
  const s = String(text ?? '').replace(/\s+/g, ' ').trim()
  if (s.length <= max) return s
  const cut = s.slice(0, max)
  const space = cut.lastIndexOf(' ')
  return (space > 40 ? cut.slice(0, space) : cut) + '...'
}

const dataDir = join(root, 'public', '_data')
rmSync(join(root, 'public'), { recursive: true, force: true })
mkdirSync(join(dataDir, 'examples'), { recursive: true })

// One asset per demo: fetching a single source must not pull 5 MB of the other
// 372 into the isolate.
for (const e of examples) {
  const safe = e.id.replace(/[^a-zA-Z0-9._-]/g, '_')
  writeFileSync(
    join(dataDir, 'examples', `${safe}.json`),
    JSON.stringify({ id: e.id, path: e.path, title: e.title, blurb: e.blurb, source: e.source }),
  )
}

// One asset for all doc bodies: search has to read every page anyway, and
// get_doc then answers from the same cached copy.
writeFileSync(
  join(dataDir, 'docs.json'),
  JSON.stringify(
    docs.map((d) => ({ slug: d.slug, title: d.title, section: d.section, markdown: d.markdown })),
  ),
)

const bundled = {
  examples: examples.map((e) => ({
    id: e.id,
    title: e.title,
    category: e.category,
    blurb: trimBlurb(e.blurb),
  })),
  docs: docs.map((d) => ({ slug: d.slug, title: d.title, section: d.section })),
  apiReference,
  apiSurface,
}

const generatedDir = join(root, 'src', 'generated')
mkdirSync(generatedDir, { recursive: true })

// The validator and the doc ranking are shared with the npm server, and this
// directory is where the Worker's copy comes from. `workers/` sits outside the
// pnpm workspace (same as svgrid-vote), so a `workspace:^` dependency is not
// available here; copying the built artifact keeps one source of truth without
// dragging the worker into the root install.
for (const file of ['validate.js', 'validate.d.ts', 'search.js', 'search.d.ts']) {
  copyFileSync(join(mcpDist, file), join(generatedDir, file))
}

// Emitted as .js + .d.ts rather than .ts so every consumer resolves it the
// same way: the bundler, tsc, and a plain `node` harness that only strips
// types (which will not map a ./x.js specifier onto an x.ts file).
writeFileSync(
  join(generatedDir, 'index.js'),
  `// Generated by scripts/build-data.mjs. Do not edit by hand.\n` +
    `/* eslint-disable */\n` +
    `export const examples = ${JSON.stringify(bundled.examples)}\n\n` +
    `export const docs = ${JSON.stringify(bundled.docs)}\n\n` +
    `export const apiReference = ${JSON.stringify(bundled.apiReference)}\n\n` +
    `export const apiSurface = ${JSON.stringify(bundled.apiSurface)}\n`,
)

writeFileSync(
  join(generatedDir, 'index.d.ts'),
  `// Generated by scripts/build-data.mjs. Do not edit by hand.\n` +
    `import type { ApiSurface } from './validate.js'\n\n` +
    `export type ExampleListing = { id: string; title: string; category: string; blurb: string }\n` +
    `export type DocListing = { slug: string; title: string; section: string }\n\n` +
    `export declare const examples: readonly ExampleListing[]\n` +
    `export declare const docs: readonly DocListing[]\n` +
    `export declare const apiReference: Readonly<Record<string, readonly string[]>>\n` +
    `export declare const apiSurface: ApiSurface\n`,
)

const kb = (n) => `${Math.round(n / 1024)} KB`
console.log(
  `build-data: bundled ${bundled.examples.length} example listings + ${bundled.docs.length} doc listings ` +
    `(${kb(JSON.stringify(bundled).length)}); ` +
    `assets: ${examples.length} demo sources + docs.json (${kb(JSON.stringify(docs).length)})`,
)
