/**
 * A compact, faithful slice of the classic **Northwind** sample database as
 * portable Postgres DDL + seed data. It is pure SQL text, so the exact same
 * script seeds:
 *   - PGlite (WASM Postgres in the browser) - see demo 338
 *   - a hosted Supabase / Postgres project - see docs/enterprise/studio + the
 *     Supabase sample kit
 *
 * Explicit primary keys (not SERIAL defaults) keep the cross-table foreign
 * keys stable and let the script run idempotently after `DROP ... CASCADE`.
 * `order_lines` is a denormalized VIEW joining order_details -> orders ->
 * customers -> products -> categories: the rich, real-world relational grid a
 * single flat table can't show.
 */

export const NORTHWIND_SQL = `
DROP VIEW IF EXISTS order_lines;
DROP TABLE IF EXISTS order_details, orders, products, customers, categories CASCADE;

CREATE TABLE categories (
  id   INTEGER PRIMARY KEY,
  name TEXT NOT NULL
);

-- customers / products use GENERATED BY DEFAULT AS IDENTITY: the seed inserts
-- explicit ids (stable FKs), and rows created later through the grid get an
-- auto id. The sequence is RESTARTed past the seed below so there's no clash.
CREATE TABLE customers (
  id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company TEXT NOT NULL,
  contact TEXT,
  city    TEXT,
  country TEXT
);

CREATE TABLE products (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           TEXT NOT NULL,
  category_id    INTEGER REFERENCES categories(id),
  unit_price     DOUBLE PRECISION NOT NULL,
  units_in_stock INTEGER NOT NULL DEFAULT 0,
  discontinued   BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE orders (
  id           INTEGER PRIMARY KEY,
  customer_id  INTEGER REFERENCES customers(id),
  order_date   DATE NOT NULL,
  ship_country TEXT
);

CREATE TABLE order_details (
  id         INTEGER PRIMARY KEY,
  order_id   INTEGER REFERENCES orders(id),
  product_id INTEGER REFERENCES products(id),
  quantity   INTEGER NOT NULL,
  unit_price DOUBLE PRECISION NOT NULL
);

INSERT INTO categories (id, name) VALUES
  (1,'Beverages'),(2,'Condiments'),(3,'Confections'),(4,'Dairy Products'),
  (5,'Grains/Cereals'),(6,'Meat/Poultry'),(7,'Produce'),(8,'Seafood');

INSERT INTO customers (id, company, contact, city, country) VALUES
  (1,'Alfreds Futterkiste','Maria Anders','Berlin','Germany'),
  (2,'Ana Trujillo Emparedados','Ana Trujillo','México D.F.','Mexico'),
  (3,'Antonio Moreno Taquería','Antonio Moreno','México D.F.','Mexico'),
  (4,'Around the Horn','Thomas Hardy','London','UK'),
  (5,'Berglunds snabbköp','Christina Berglund','Luleå','Sweden'),
  (6,'Blauer See Delikatessen','Hanna Moos','Mannheim','Germany'),
  (7,'Bólido Comidas preparadas','Martín Sommer','Madrid','Spain'),
  (8,'Bon app''','Laurence Lebihan','Marseille','France'),
  (9,'Bottom-Dollar Markets','Elizabeth Lincoln','Tsawassen','Canada'),
  (10,'B''s Beverages','Victoria Ashworth','London','UK');

INSERT INTO products (id, name, category_id, unit_price, units_in_stock, discontinued) VALUES
  (1,'Chai',1,18.00,39,false),
  (2,'Chang',1,19.00,17,false),
  (3,'Aniseed Syrup',2,10.00,13,false),
  (4,'Chef Anton''s Cajun Seasoning',2,22.00,53,false),
  (5,'Grandma''s Boysenberry Spread',2,25.00,120,false),
  (6,'Uncle Bob''s Organic Dried Pears',7,30.00,15,false),
  (7,'Northwoods Cranberry Sauce',2,40.00,6,false),
  (8,'Mishi Kobe Niku',6,97.00,29,true),
  (9,'Ikura',8,31.00,31,false),
  (10,'Queso Cabrales',4,21.00,22,false),
  (11,'Konbu',8,6.00,24,false),
  (12,'Tofu',7,23.25,35,false),
  (13,'Genen Shouyu',2,15.50,39,false),
  (14,'Pavlova',3,17.45,29,false),
  (15,'Alice Mutton',6,39.00,0,true),
  (16,'Carnarvon Tigers',8,62.50,42,false);

-- Move the identity sequences past the seeded ids so grid-created rows don't collide.
ALTER TABLE customers ALTER COLUMN id RESTART WITH 1000;
ALTER TABLE products  ALTER COLUMN id RESTART WITH 1000;

INSERT INTO orders (id, customer_id, order_date, ship_country) VALUES
  (10248,5,'2023-07-04','Sweden'),
  (10249,6,'2023-07-05','Germany'),
  (10250,3,'2023-07-08','Mexico'),
  (10251,7,'2023-07-08','Spain'),
  (10252,9,'2023-07-09','Canada'),
  (10253,3,'2023-07-10','Mexico'),
  (10254,10,'2023-07-11','UK'),
  (10255,1,'2023-07-12','Germany'),
  (10256,5,'2023-07-15','Sweden'),
  (10257,4,'2023-07-16','UK');

INSERT INTO order_details (id, order_id, product_id, quantity, unit_price) VALUES
  (1,10248,11,12,6.00),(2,10248,14,10,17.45),(3,10248,1,5,18.00),
  (4,10249,8,9,97.00),(5,10249,16,40,62.50),
  (6,10250,9,10,31.00),(7,10250,12,35,23.25),(8,10250,2,15,19.00),
  (9,10251,6,6,30.00),(10,10251,13,15,15.50),
  (11,10252,5,40,25.00),(12,10252,10,25,21.00),
  (13,10253,3,20,10.00),(14,10253,4,42,22.00),(15,10253,1,40,18.00),
  (16,10254,16,15,62.50),(17,10254,11,21,6.00),
  (18,10255,2,20,19.00),(19,10255,9,35,31.00),(20,10255,14,25,17.45),
  (21,10256,7,15,40.00),(22,10256,5,12,25.00),
  (23,10257,12,25,23.25),(24,10257,6,6,30.00);

CREATE VIEW order_lines AS
  SELECT
    d.id                     AS id,
    d.order_id               AS order_id,
    o.order_date             AS order_date,
    c.company                AS customer,
    p.name                   AS product,
    cat.name                 AS category,
    d.quantity               AS quantity,
    d.unit_price             AS unit_price,
    (d.quantity * d.unit_price) AS line_total,
    o.ship_country           AS ship_country
  FROM order_details d
  JOIN orders o     ON o.id = d.order_id
  JOIN customers c  ON c.id = o.customer_id
  JOIN products p   ON p.id = d.product_id
  JOIN categories cat ON cat.id = p.category_id;
`

import type { EntitySchema } from '@svgrid/enterprise'

export type Product = {
  id: number
  name: string
  category_id: number
  unit_price: number
  units_in_stock: number
  discontinued: boolean
}

export type Customer = {
  id: number
  company: string
  contact: string
  city: string
  country: string
}

/** A row of the `order_lines` view - read-only (a five-table join). */
export type OrderLine = {
  id: number
  order_id: number
  order_date: string
  customer: string
  product: string
  category: string
  quantity: number
  unit_price: number
  line_total: number
  ship_country: string
}

export const productsSchema: EntitySchema<Product> = {
  name: 'products',
  label: 'Product',
  idField: 'id',
  fields: [
    { field: 'id', type: 'number', primaryKey: true, readonly: true },
    { field: 'name', type: 'text', label: 'Product', required: true, minLength: 2 },
    { field: 'category_id', type: 'number', label: 'Category #', min: 1, max: 8 },
    { field: 'unit_price', type: 'number', label: 'Unit Price ($)', min: 0 },
    { field: 'units_in_stock', type: 'number', label: 'In Stock', min: 0 },
    { field: 'discontinued', type: 'boolean' },
  ],
}

export const customersSchema: EntitySchema<Customer> = {
  name: 'customers',
  label: 'Customer',
  idField: 'id',
  fields: [
    { field: 'id', type: 'number', primaryKey: true, readonly: true },
    { field: 'company', type: 'text', label: 'Company', required: true, minLength: 2 },
    { field: 'contact', type: 'text', label: 'Contact' },
    { field: 'city', type: 'text', label: 'City' },
    { field: 'country', type: 'text', label: 'Country' },
  ],
}

/** The joined view: every field read-only (you don't write to a JOIN). */
export const orderLinesSchema: EntitySchema<OrderLine> = {
  name: 'order_lines',
  label: 'Order line',
  idField: 'id',
  fields: [
    { field: 'id', type: 'number', primaryKey: true, readonly: true },
    { field: 'order_id', type: 'number', label: 'Order #', readonly: true },
    { field: 'order_date', type: 'dateString', label: 'Date', readonly: true },
    { field: 'customer', type: 'text', label: 'Customer', readonly: true },
    { field: 'product', type: 'text', label: 'Product', readonly: true },
    { field: 'category', type: 'text', label: 'Category', readonly: true },
    { field: 'quantity', type: 'number', label: 'Qty', readonly: true },
    { field: 'unit_price', type: 'number', label: 'Unit Price ($)', readonly: true },
    { field: 'line_total', type: 'number', label: 'Line Total ($)', readonly: true },
    { field: 'ship_country', type: 'text', label: 'Ship To', readonly: true },
  ],
}
