/**
 * AUTO-GENERATED by scripts/generate-wrappers.mjs - DO NOT EDIT.
 * Regenerate: pnpm --filter @svgrid/grid-wc generate:wrappers
 *
 * Type declarations for the <sv-chart> custom element.
 */

/**
 * The chart element's own surface. `spec` is `unknown` here rather than
 * wrong: import `ChartSpec` from `@svgrid/grid` when you want it checked.
 */
export interface SvChartElement extends HTMLElement {
  /** property only - an attribute cannot hold this */
  spec: unknown
  /** attribute `legend` */
  legend: string
  /** attribute `interactive` */
  interactive: boolean
  /** attribute `data-labels` */
  dataLabels: boolean
  /** property only - an attribute cannot hold this */
  formatValue: unknown
  /** property only - an attribute cannot hold this */
  tooltipFormat: unknown
  /** attribute `tooltip-mode` */
  tooltipMode: "shared" | "single"
  /** attribute `tooltip-position` */
  tooltipPosition: "follow" | "top-left" | "top-right" | "bottom-left" | "bottom-right"
  /** attribute `tooltip-sticky` */
  tooltipSticky: boolean
  /** attribute `zoomable` */
  zoomable: boolean
  /** property only - an attribute cannot hold this */
  zoom: unknown
  /** attribute `range-presets` */
  rangePresets: boolean
  /** attribute `sync-group` */
  syncGroup: string
  /** attribute `context-menu` */
  contextMenu: boolean
  /** attribute `animate` */
  animate: boolean
  /** attribute `live` */
  live: boolean
  /** attribute `drillable` */
  drillable: boolean
  /** property only - an attribute cannot hold this */
  drillPath: readonly unknown[]
  /** attribute `selectable` */
  selectable: string
  /** property only - an attribute cannot hold this */
  selected: readonly unknown[]
  /** attribute `hover-highlight` */
  hoverHighlight: boolean
  /** attribute `announce` */
  announce: boolean
  /** attribute `describe` */
  describe: boolean
  /** property only - an attribute cannot hold this */
  localeText: unknown
  /** attribute `crosshair-labels` */
  crosshairLabels: boolean
  /** attribute `brush` */
  brush: boolean
  /** attribute `brush-height` */
  brushHeight: number
  /** attribute `toolbar` */
  toolbar: boolean
  /** attribute `width` */
  width: number
  /** attribute `height` */
  height: number
  /** attribute `autosize` */
  autosize: boolean
  /** attribute `annotatable` */
  annotatable: boolean
  /** attribute `drawable` */
  drawable: boolean
}

declare global {
  interface HTMLElementTagNameMap {
    'sv-chart': SvChartElement
  }

  interface HTMLElementEventMap {
    select: CustomEvent<unknown>
    drill: CustomEvent<unknown>
    zoom: CustomEvent<unknown>
    selectionchange: CustomEvent<unknown>
    hover: CustomEvent<unknown>
    annotate: CustomEvent<unknown>
    annotationremove: CustomEvent<unknown>
    drawingschange: CustomEvent<unknown>
  }
}

export {}
