/**
 * AUTO-GENERATED by scripts/generate-wrappers.mjs - DO NOT EDIT.
 * Regenerate: pnpm --filter @svgrid/grid-wc generate:wrappers
 *
 * Type declarations for the custom elements.
 */

/**
 * The custom element's own surface. Complex props (columns, data, configs)
 * are `unknown` here rather than wrong: their real types are generic over
 * the feature set and the row type, which cannot be reproduced outside
 * `@svgrid/grid`. Import them from there when you want them checked.
 */
export interface SvGridElement extends HTMLElement {
  /** property only - an attribute cannot hold this */
  data: readonly unknown[]
  /** property only - an attribute cannot hold this */
  columns: readonly unknown[]
  /** property only - an attribute cannot hold this */
  board: unknown
  /** property only - an attribute cannot hold this */
  scheduler: unknown
  /** property only - an attribute cannot hold this */
  chart: unknown
  /** property only - an attribute cannot hold this */
  pivot: unknown
  /** attribute `pivot-mode` */
  pivotMode: boolean
  /** attribute `context-menu` */
  contextMenu: boolean
  /** attribute `selection-bar` */
  selectionBar: boolean
  /** property only - an attribute cannot hold this */
  features: unknown
  /** attribute `sortable` */
  sortable: boolean
  /** attribute `filterable` */
  filterable: boolean
  /** attribute `editable` */
  editable: boolean
  /** property only - an attribute cannot hold this */
  treeData: unknown
  /** attribute `groupable` */
  groupable: boolean
  /** property only - an attribute cannot hold this */
  groupBy: readonly unknown[]
  /** property only - an attribute cannot hold this */
  expanded: unknown
  /** attribute `group-footers` */
  groupFooters: boolean
  /** attribute `grand-total-row` */
  grandTotalRow: boolean
  /** attribute `group-display-mode` */
  groupDisplayMode: string
  /** attribute `auto-group-column-header` */
  autoGroupColumnHeader: string
  /** attribute `auto-group-column-width` */
  autoGroupColumnWidth: number
  /** attribute `pageable` */
  pageable: boolean
  /** attribute `loading` */
  loading: boolean
  /** attribute `loading-overlay` */
  loadingOverlay: boolean
  /** attribute `loading-skeleton-rows` */
  loadingSkeletonRows: number
  /** attribute `error` */
  error: string | null
  /** attribute `empty-message` */
  emptyMessage: string
  /** property only - an attribute cannot hold this */
  localization: unknown
  /** attribute `show-global-filter` */
  showGlobalFilter: boolean
  /** attribute `show-column-filters` */
  showColumnFilters: boolean
  /** attribute `filter-mode` */
  filterMode: "row" | "menu" | "global" | "none"
  /** attribute `show-grouping-controls` */
  showGroupingControls: boolean
  /** attribute `show-row-selection` */
  showRowSelection: boolean
  /** attribute `show-pagination` */
  showPagination: boolean
  /** attribute `page-size` */
  pageSize: number
  /** property only - an attribute cannot hold this */
  pageSizeOptions: readonly unknown[]
  /** attribute `pagination-position` */
  paginationPosition: "top" | "bottom" | "both"
  /** attribute `external-pagination` */
  externalPagination: boolean
  /** attribute `row-count` */
  rowCount: number
  /** attribute `page-index` */
  pageIndex: number
  /** attribute `virtualization` */
  virtualization: boolean
  /** attribute `row-height` */
  rowHeight: number
  /** attribute `auto-row-height` */
  autoRowHeight: boolean
  /** attribute `row-resize` */
  rowResize: boolean
  /** attribute `header-height` */
  headerHeight: number
  /** attribute `overscan` */
  overscan: number
  /** attribute `container-height` */
  containerHeight: string
  /** attribute `column-virtualization` */
  columnVirtualization: boolean
  /** attribute `column-overscan` */
  columnOverscan: number
  /** attribute `column-width` */
  columnWidth: number
  /** property only - an attribute cannot hold this */
  initialColumnPinning: unknown
  /** attribute `fit-columns` */
  fitColumns: boolean
  /** attribute `column-resize` */
  columnResize: boolean
  /** attribute `responsive` */
  responsive: boolean
  /** attribute `show-filter-menu` */
  showFilterMenu: boolean
  /** attribute `show-filter-row` */
  showFilterRow: boolean
  /** attribute `enable-cell-selection` */
  enableCellSelection: boolean
  /** attribute `move-cells` */
  moveCells: boolean
  /** attribute `enable-row-hover` */
  enableRowHover: boolean
  /** attribute `copy-headers-to-clipboard` */
  copyHeadersToClipboard: boolean
  /** property only - an attribute cannot hold this */
  processCellForClipboard: unknown
  /** attribute `enable-inline-editing` */
  enableInlineEditing: boolean
  /** attribute `full-row-editing` */
  fullRowEditing: boolean
  /** attribute `enable-row-summaries` */
  enableRowSummaries: boolean
  /** attribute `summary` */
  summary: boolean
  /** attribute `status-bar` */
  statusBar: boolean
  /** attribute `tool-panel` */
  toolPanel: boolean
  /** attribute `charting` */
  charting: boolean
  /** attribute `column-menu-tabs` */
  columnMenuTabs: boolean
  /** attribute `tool-panel-default-open` */
  toolPanelDefaultOpen: boolean
  /** attribute `tool-panel-default-tab` */
  toolPanelDefaultTab: "columns" | "filters"
  /** attribute `selection-mode` */
  selectionMode: "row" | "cell" | "both" | "none"
  /** attribute `show-row-numbers` */
  showRowNumbers: boolean
  /** attribute `zebra-rows` */
  zebraRows: boolean
  /** attribute `row-number-width` */
  rowNumberWidth: number
  /** attribute `external-sort` */
  externalSort: boolean
  /** property only - an attribute cannot hold this */
  initialSorting: readonly unknown[]
  /** property only - an attribute cannot hold this */
  initialAdvancedFilter: unknown
  /** attribute `external-filter` */
  externalFilter: boolean
  /** property only - an attribute cannot hold this */
  getRowId: unknown
  /** property only - an attribute cannot hold this */
  rowClass: unknown
  /** property only - an attribute cannot hold this */
  notes: unknown
  /** attribute `editable-comments` */
  editableComments: boolean
  /** property only - an attribute cannot hold this */
  conditionalFormats: readonly unknown[]
  /** attribute `conditional-stat-scope` */
  conditionalStatScope: "filtered" | "visible" | "all"
  /** property only - an attribute cannot hold this */
  isDetailRow: unknown
  /** property only - an attribute cannot hold this */
  serverGroup: unknown
  /** property only - an attribute cannot hold this */
  serverFilterValues: unknown
  /** property only - an attribute cannot hold this */
  pinnedTopRows: readonly unknown[]
  /** property only - an attribute cannot hold this */
  pinnedBottomRows: readonly unknown[]
  /** attribute `enable-column-reorder` */
  enableColumnReorder: boolean
  /** property only - an attribute cannot hold this */
  columnOrder: readonly unknown[]
  /** attribute `infer-column-types` */
  inferColumnTypes: boolean
  /** attribute `row-drag-managed` */
  rowDragManaged: boolean
  /** attribute `row-drag-group` */
  rowDragGroup: string
  /** attribute `aligned-grid-group` */
  alignedGridGroup: string
  /** attribute `filter-locale` */
  filterLocale: string

  /** The grid api. Present once `apiready` has fired. */
  readonly api: unknown
}

declare global {
  interface HTMLElementTagNameMap {
    'sv-grid': SvGridElement
    'sv-grid-shadow': SvGridElement
  }

  interface HTMLElementEventMap {
    pivotmodechange: CustomEvent<unknown>
    expandedchange: CustomEvent<unknown>
    paginationchange: CustomEvent<unknown>
    apiready: CustomEvent<unknown>
    rowselectionchange: CustomEvent<unknown>
    cellselectionchange: CustomEvent<unknown>
    sortingchange: CustomEvent<unknown>
    advancedfilterchange: CustomEvent<unknown>
    filterschange: CustomEvent<unknown>
    notechange: CustomEvent<unknown>
    cellvaluechange: CustomEvent<unknown>
    activecellchange: CustomEvent<unknown>
    cellclick: CustomEvent<unknown>
    rowclick: CustomEvent<unknown>
    celldoubleclick: CustomEvent<unknown>
    rowdoubleclick: CustomEvent<unknown>
    scrollbottomreached: CustomEvent<unknown>
    columnorderchange: CustomEvent<unknown>
    rowdragend: CustomEvent<unknown>
    selectionchange: CustomEvent<unknown>
  }
}

export {}
