/**
 * `@svgrid/enterprise/studio` - the pure, Svelte-free Studio core. Introspect a
 * data source into an `EntitySchema`, then scaffold runnable SvelteKit code
 * from it. Importable from Node (the MCP generator) as well as bundlers (the
 * visual designer), since nothing here touches Svelte or the DOM.
 */
export { inferType, introspectJson, introspectDrizzle, introspectDrizzleAll } from './introspect.js'
export { refineField, refineFields } from '../sources/field-inference.js'
export { parseCsv, detectDelimiter, csvToEntity, type CsvEntity } from './csv.js'
export { introspectPrisma, introspectPrismaAll } from './introspect-prisma.js'
export {
  introspectDatabase,
  listDatabaseTables,
  countTableRows,
  probeConnection,
  mapSqlType,
  type SqlDialectName,
  type DbExecute,
  type IntrospectDbOptions,
  type TableRowCount,
} from './introspect-db.js'
export {
  buildConnectionString,
  parseConnectionString,
  redactConnectionString,
  isFileDialect,
  DRIVER_PACKAGE,
  DEFAULT_PORT,
  type SqlConnectionParts,
} from './db-connect-string.js'
export {
  scaffold,
  mergeManaged,
  skipUserOwned,
  MANAGED_START,
  MANAGED_END,
  type GeneratedFile,
  type ScaffoldOptions,
} from './scaffold.js'
export { scaffoldApp, type ScaffoldAppOptions } from './scaffold-app.js'
export { emitStudioApp, emitEntityModules, entityScreenPage, prepareEntities } from './emit-schema.js'
export { emitStudioProject, emitStudioAppBundle, studioDeployInfo, screenHandles, screenDataset, ctxCompletions, componentHandleMembers, ctxAmbientDts, GRID_API_MEMBERS, type BlockHandle, type HandleTier } from './emit-project.js'
export { sampleApps, getSampleApp, type SampleApp } from './samples/index.js'
export { liveDataSamples, getLiveDataSample } from './samples/live-data.js'
export {
  sanitizeStudioProject,
  buildStudioBugReport,
  type SanitizeResult,
  type BugReport,
  type BugReportInput,
  type StudioEnv,
} from './bug-report.js'
export { generateValue, generateRows } from './sample-data.js'
export { studioThemes, defaultStudioTheme, getStudioTheme, resolveThemeTokens, resolveThemeTokensFor, isDarkTheme, themeStyleString, type StudioTheme } from './themes.js'
export {
  createProject,
  defaultScreenFor,
  defaultBlockConfig,
  gridColumns,
  entityOf,
  blockPalette,
  addBlock,
  addBlockAt,
  addComponentBlock,
  removeBlock,
  duplicateBlock,
  moveBlock,
  reorderBlock,
  updateBlock,
  addEntity,
  removeEntity,
  updateEntity,
  addScreen,
  addFreestandingScreen,
  addScreenAction,
  removeScreenAction,
  enableScreenCode,
  disableScreenCode,
  setScreenRenderGrid,
  setHandlerBody,
  setScreenHandlersSource,
  setComponentName,
  componentHandleName,
  ON_LOAD,
  removeScreen,
  updateScreen,
  duplicateScreen,
  reorderScreen,
  insertBlock,
  setDataSource,
  setDeployTarget,
  defaultEntitySource,
  flattenBlocks,
  TAB_CHILD_KINDS,
  addTab,
  removeTab,
  renameTab,
  addTabBlock,
  removeTabBlock,
  setEntityDataSource,
  entityDataSource,
  setTheme,
  setThemePreset,
  setShell,
  sanitizeProject,
  screenFromTemplate,
  addScreenFromTemplate,
  serializeProject,
  parseProject,
  validateProject,
  isProjectValid,
  blockColumns,
  blockStyleCss,
  blockClassName,
  sanitizeClassName,
  mergeBlockStyle,
  type BlockStyle,
  roleCanScreen,
  roleCanAction,
  CRUD_ACTIONS,
  type CrudAction,
  type RoleAccess,
  type AccessControl,
  type I18nConfig,
  type DeployTarget,
  type StudioProject,
  type Screen,
  type ScreenNav,
  type Block,
  type BlockKind,
  type BlockConfig,
  type GridConfig,
  type GridColumnConfig,
  type RowLink,
  type RowAction,
  type RowActionKind,
  type ActionConfig,
  type ComponentConfig,
  type FormatOp,
  type FormatRule,
  type GridEditing,
  type GridDensity,
  type GridAlign,
  type PagerPosition,
  type FormConfig,
  type ChartConfig,
  type KpiConfig,
  type KpiFormat,
  type GaugeConfig,
  type TreeConfig,
  type TabsConfig,
  type StudioTab,
  type DashboardConfig,
  type MasterDetailConfig,
  type LookupConfig,
  type PivotConfig,
  type FilterPanelConfig,
  type RecordConfig,
  type BoardConfig,
  type CalendarConfig,
  type DetailConfig,
  type DetailRelated,
  type Reduce,
  type DataSourceKind,
  type EntityDataSource,
  type MemorySource,
  type RestSource,
  type SqlSource,
  type SupabaseSource,
  type PgliteSource,
  type RestMethod,
  type ParamLocation,
  type ParamType,
  type RequestParam,
  type SqlDialectKind,
  type ProjectTheme,
  type ShellConfig,
  type ShellStyle,
  type ScreenTemplate,
  type PaletteItem,
  type ProjectIssue,
} from './project.js'
export {
  verifyScaffold,
  summarizeVerify,
  type VerifyResult,
  type VerifyIssue,
  type VerifySeverity,
} from './verify.js'
export {
  UI_COMPONENT_REGISTRY,
  uiComponentSpec,
  type UiPropType,
  type UiComponentProp,
  type UiComponentSpec,
} from './ui-components.js'
export {
  runStudioAdd,
  runStudioAddApp,
  resolveSchema,
  resolveSchemas,
  type StudioIO,
  type AddOptions,
  type AddResult,
  type AddAppResult,
} from './cli.js'

// Re-export the schema surface so consumers get everything from one entry.
export {
  resolveIdField,
  schemaToColumns,
  schemaToFormFields,
  linkRelationLabels,
  pickLabelField,
  type EntitySchema,
  type EntityField,
  type EntityFieldType,
} from '../schema.js'

// Pure license classification, so the Node/MCP generator can soft-gate with the
// same rules as the browser (see license-core.ts). No DOM, safe in Node.
export { checkLicenseKey, type LicenseInfo, type LicenseStatus } from '../license-core.js'
