/**
 * scaffoldApp - scaffold a whole data app, not a single page. Given several
 * `EntitySchema`s (e.g. every table from `introspectDatabase` + `--all`), it
 * emits each entity's screen (via `scaffold`) plus a shared **navigation
 * layout** and a **home page** linking them. It also runs `linkRelationLabels`
 * across the set, so foreign-key lookups resolve their display field from the
 * actual related schema and every relation's `/api/<entity>` route exists.
 *
 * Pure string building, like `scaffold`. Each generated shell file wraps its
 * body in `svgrid:managed` markers so re-running is safe.
 */
import { linkRelationLabels, titleCase, type EntitySchema } from '../schema.js'
import { scaffold, MANAGED_START, MANAGED_END, type GeneratedFile, type ScaffoldOptions } from './scaffold.js'

export type ScaffoldAppOptions = {
  /** Backend for every entity's API route (see `ScaffoldOptions.dataSource`). */
  dataSource?: ScaffoldOptions['dataSource']
  /** App title shown in the nav + home. Default `'Data App'`. */
  appTitle?: string
}

type NavItem = { href: string; label: string }

const MANAGED_NOTE = '// Regenerated by SvGrid Studio. Edits inside these markers are overwritten.'
const managed = (body: string) => `${MANAGED_START}\n${MANAGED_NOTE}\n${body}\n${MANAGED_END}`

function layoutFile(nav: NavItem[], appTitle: string): GeneratedFile {
  return {
    path: 'src/routes/+layout.svelte',
    description: 'App shell: a nav sidebar linking every entity screen, with the routed page in the main area.',
    contents: `<script lang="ts">
${managed(`  let { children } = $props()
  const appTitle = ${JSON.stringify(appTitle)}
  const nav = ${JSON.stringify(nav)}`)}
</script>

<div class="app-shell">
  <aside class="app-shell__nav">
    <a class="app-shell__brand" href="/">{appTitle}</a>
    <nav>
      {#each nav as item (item.href)}
        <a class="app-shell__link" href={item.href}>{item.label}</a>
      {/each}
    </nav>
  </aside>
  <main class="app-shell__main">
    {@render children?.()}
  </main>
</div>

<style>
  .app-shell { display: grid; grid-template-columns: 220px 1fr; min-height: 100vh; }
  .app-shell__nav { display: flex; flex-direction: column; gap: 4px; padding: 16px 12px; border-right: 1px solid #e5e7eb; background: #f8fafc; }
  .app-shell__brand { font-weight: 700; font-size: 16px; padding: 6px 10px 12px; color: inherit; text-decoration: none; }
  .app-shell__link { padding: 8px 10px; border-radius: 6px; color: #334155; text-decoration: none; }
  .app-shell__link:hover { background: #e2e8f0; }
  .app-shell__main { padding: 20px 24px; min-width: 0; }
</style>
`,
  }
}

function homeFile(nav: NavItem[], appTitle: string): GeneratedFile {
  return {
    path: 'src/routes/+page.svelte',
    description: 'Home page: cards linking to each entity screen.',
    contents: `<script lang="ts">
${managed(`  const appTitle = ${JSON.stringify(appTitle)}
  const entities = ${JSON.stringify(nav)}`)}
</script>

<section class="home">
  <h2 class="home__title">{appTitle}</h2>
  <div class="home__grid">
    {#each entities as item (item.href)}
      <a class="home__card" href={item.href}>{item.label}</a>
    {/each}
  </div>
</section>

<style>
  .home__title { margin: 0 0 16px; font-size: 20px; font-weight: 600; }
  .home__grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(180px, 1fr)); gap: 12px; }
  .home__card { display: block; padding: 18px 16px; border: 1px solid #e5e7eb; border-radius: 10px; color: inherit; text-decoration: none; font-weight: 600; }
  .home__card:hover { border-color: #94a3b8; background: #f8fafc; }
</style>
`,
  }
}

export function scaffoldApp(
  schemas: EntitySchema[],
  options: ScaffoldAppOptions = {},
): { files: GeneratedFile[] } {
  if (schemas.length === 0) throw new Error('scaffoldApp: no schemas to scaffold')
  const appTitle = options.appTitle ?? 'Data App'

  // Resolve each relation's display field against the related schema in the set.
  const linked = linkRelationLabels(schemas)

  const files: GeneratedFile[] = []
  for (const schema of linked) {
    files.push(...scaffold(schema, { dataSource: options.dataSource }).files)
  }

  const nav: NavItem[] = linked.map((s) => ({ href: `/${s.name}`, label: s.label ?? titleCase(s.name) }))
  files.push(layoutFile(nav, appTitle), homeFile(nav, appTitle))
  return { files }
}
