/**
 * AUTO-GENERATED by scripts/generate-sheet-surface.mjs - DO NOT EDIT.
 * Regenerate: pnpm --filter @svgrid/enterprise generate:wc
 *
 * Type declarations for the <sv-sheet> custom element.
 */

/**
 * The element's own surface. The document, the workbook and the formats
 * are `unknown` here rather than wrong: import their types from
 * `@svgrid/enterprise` when you want them checked.
 */
export interface SvSheetElement extends HTMLElement {
  /** property only - an attribute cannot hold this */
  document: unknown
  /** property only - an attribute cannot hold this */
  workbook: unknown
  /** property only - an attribute cannot hold this */
  data: readonly unknown[]
  /** property only - an attribute cannot hold this */
  gridSheets: unknown
  /** attribute `rows` */
  rows: number
  /** attribute `columns` */
  columns: number
  /** attribute `height` */
  height: number | "100%"
  /** attribute `column-width` */
  columnWidth: number
  /** attribute `row-height` */
  rowHeight: number
  /** attribute `look` */
  look: "excel" | "theme"
  /** property only - an attribute cannot hold this */
  columnWidths: unknown
  /** property only - an attribute cannot hold this */
  formats: unknown
  /** property only - an attribute cannot hold this */
  extras: readonly unknown[]
  /** property only - an attribute cannot hold this */
  localization: unknown
  /** attribute `comment-author` */
  commentAuthor: string
  /** attribute `show-ribbon` */
  showRibbon: boolean
  /** attribute `show-formula-bar` */
  showFormulaBar: boolean
  /** attribute `show-tabs` */
  showTabs: boolean
  /** attribute `show-status-bar` */
  showStatusBar: boolean
  /** property only - an attribute cannot hold this */
  presence: readonly unknown[]
  /** The grid api, set before `ready` fires. */
  api: unknown
  /** The sheet document, set before `ready` fires. */
  document: unknown
  /** The document as plain JSON. */
  getState(): SheetState
  /** Put a saved document back. */
  setState(state: SheetState): void
  /** Repaint after a write the shell could not see. */
  refresh(): void
  /** Run a ribbon action as if its button had been clicked. */
  act(action: RibbonActionId): void
  /** Replace the document with an .xlsx, .ods or .csv file. */
  open(file: Blob & { name?: string }): Promise<void>
  /** The document as an .xlsx Blob. */
  toXlsx(): Promise<Blob>
  /** The document as an .ods Blob, which LibreOffice Calc opens. */
  toOds(): Promise<Blob>
  /** The document as an .xls Blob, which Excel 97-2003 opens. */
  toXls(): Blob
  /** The active sheet as CSV. */
  toCsv(): string
  /** Start over with one empty sheet. */
  newWorkbook(): void
  /** The active sheet in the print dialog. */
  print(): void
  /** The page File > Print would open. */
  printHtml(): string
}

/** `detail` of each event. `action` is cancelable: `preventDefault()` takes the action over, as returning true from `onAction` does. */
export interface SvSheetEventMap {
  action: CustomEvent<{ action: unknown; cmd: unknown }>
  cellaction: CustomEvent<unknown>
  ready: CustomEvent<{ api: unknown; document: unknown }>
  change: CustomEvent<unknown>
  presence: CustomEvent<unknown>
}

declare global {
  interface HTMLElementTagNameMap {
    'sv-sheet': SvSheetElement
  }
}
