/**
 * AUTO-GENERATED by scripts/generate-sheet-surface.mjs - DO NOT EDIT.
 * Regenerate: pnpm --filter @svgrid/enterprise generate:wc
 *
 * Declarations for the React wrapper.
 */
import type { ForwardRefExoticComponent, RefAttributes } from 'react'
export interface SvSheetProps {
  document?: unknown
  workbook?: unknown
  data?: readonly unknown[]
  rows?: number
  columns?: number
  height?: number | "100%"
  columnWidth?: number
  rowHeight?: number
  look?: "excel" | "theme"
  columnWidths?: unknown
  formats?: unknown
  extras?: readonly unknown[]
  localization?: unknown
  commentAuthor?: string
  showRibbon?: boolean
  showFormulaBar?: boolean
  showTabs?: boolean
  showStatusBar?: boolean
  presence?: readonly unknown[]
  onAction?: (detail: { action: unknown; cmd: unknown }, event: CustomEvent) => void
  onReady?: (detail: { api: unknown; document: unknown }, event: CustomEvent) => void
  onChange?: (detail: unknown, event: CustomEvent) => void
  onPresence?: (detail: unknown, event: CustomEvent) => void
  className?: string
  style?: Record<string, string | number>
}
export interface SvSheetHandle {
  element: (HTMLElement & Record<string, unknown>) | null
}
export declare const SvSheet: ForwardRefExoticComponent<SvSheetProps & RefAttributes<SvSheetHandle>>
export default SvSheet
