/**
 * AUTO-GENERATED by scripts/generate-sheet-surface.mjs - DO NOT EDIT.
 * Regenerate: pnpm --filter @svgrid/enterprise generate:wc
 *
 * React wrapper for <sv-sheet>. Assigns object props (the document above all) as properties, which React <=18 would otherwise stringify onto attributes; the methods are reachable through the ref.
 */
import { createElement, forwardRef, useEffect, useImperativeHandle, useRef } from 'react'
import type { Ref } from 'react'
import '@svgrid/enterprise/wc'

export interface SvSheetProps {
  /** `property only` - SheetDocument */
  document?: unknown
  /** `property only` - Workbook */
  workbook?: unknown
  /** `property only` - ReadonlyArray<SheetData> */
  data?: readonly unknown[]
  /** `property only` - Record<string, GridSheetSpec> */
  gridSheets?: unknown
  /** `rows` - number */
  rows?: number
  /** `columns` - number */
  columns?: number
  /** `height` - number | '100%' */
  height?: number | "100%"
  /** `column-width` - number */
  columnWidth?: number
  /** `row-height` - number */
  rowHeight?: number
  /** `look` - 'excel' | 'theme' */
  look?: "excel" | "theme"
  /** `property only` - Readonly<Record<string, number>> */
  columnWidths?: unknown
  /** `property only` - Readonly<Record<string, CellFormatEntry>> */
  formats?: unknown
  /** `property only` - ReadonlyArray<'insert-table' | 'insert-chart'> */
  extras?: readonly unknown[]
  /** `property only` - SheetLocalization */
  localization?: unknown
  /** `comment-author` - string */
  commentAuthor?: string
  /** `show-ribbon` - boolean */
  showRibbon?: boolean
  /** `show-formula-bar` - boolean */
  showFormulaBar?: boolean
  /** `show-tabs` - boolean */
  showTabs?: boolean
  /** `show-status-bar` - boolean */
  showStatusBar?: boolean
  /** `property only` - ReadonlyArray<SheetPresence> */
  presence?: readonly unknown[]

  /** `action` - call event.preventDefault() to take the action over */
  onAction?: (detail: { action: unknown; cmd: unknown }, event: CustomEvent) => void
  /** `cellaction` */
  onCellaction?: (detail: unknown, event: CustomEvent) => void
  /** `ready` */
  onReady?: (detail: { api: unknown; document: unknown }, event: CustomEvent) => void
  /** `change` */
  onChange?: (detail: unknown, event: CustomEvent) => void
  /** `presence` */
  onPresence?: (detail: unknown, event: CustomEvent) => void

  className?: string
  style?: Record<string, string | number>
}

/** The element itself, with the sheet's methods on it. */
export interface SvSheetHandle {
  element: (HTMLElement & Record<string, unknown>) | null
}

const PROP_NAMES = ["document","workbook","data","gridSheets","rows","columns","height","columnWidth","rowHeight","look","columnWidths","formats","extras","localization","commentAuthor","showRibbon","showFormulaBar","showTabs","showStatusBar","presence"] as const
const EVENTS: Array<[handler: string, event: string]> = [["onAction","action"],["onCellaction","cellaction"],["onReady","ready"],["onChange","change"],["onPresence","presence"]]

export const SvSheet = forwardRef(function SvSheet(props: SvSheetProps, ref: Ref<SvSheetHandle>) {
  const hostRef = useRef<HTMLElement | null>(null)
  const { className, style, ...rest } = props

  const written = useRef<Record<string, unknown>>({})
  useEffect(() => {
    const el = hostRef.current as (HTMLElement & Record<string, unknown>) | null
    if (!el) return
    for (const name of PROP_NAMES) {
      const value = (rest as Record<string, unknown>)[name]
      if (value === undefined || Object.is(written.current[name], value)) continue
      written.current[name] = value
      el[name] = value
    }
  })

  const handlers = useRef(rest as Record<string, unknown>)
  handlers.current = rest as Record<string, unknown>

  useEffect(() => {
    const el = hostRef.current
    if (!el) return
    const bound: Array<[string, EventListener]> = []
    for (const [handler, event] of EVENTS) {
      const listener: EventListener = (e) => {
        const fn = handlers.current[handler] as ((detail: unknown, event: CustomEvent) => void) | undefined
        fn?.((e as CustomEvent).detail, e as CustomEvent)
      }
      el.addEventListener(event, listener)
      bound.push([event, listener])
    }
    // `ready` fires during the element's own mount, before React binds: replay it.
    const onReady = handlers.current.onReady as ((detail: unknown, event: CustomEvent) => void) | undefined
    const api = (el as HTMLElement & { api?: unknown; document?: unknown }).api
    if (onReady && api != null) onReady({ api, document: (el as HTMLElement & { document?: unknown }).document }, new CustomEvent('ready'))
    return () => { for (const [event, listener] of bound) el.removeEventListener(event, listener) }
  }, [])

  useImperativeHandle(ref, () => ({
    get element() { return hostRef.current as (HTMLElement & Record<string, unknown>) | null },
  }), [])

  return createElement('sv-sheet', { ref: hostRef, class: className, style: { display: 'block', ...style } })
})

export default SvSheet
