/**
 * AUTO-GENERATED by scripts/generate-sheet-surface.mjs - DO NOT EDIT.
 * Regenerate: pnpm --filter @svgrid/enterprise generate:wc
 *
 * Vue wrapper for <sv-sheet>. Forwards every prop as a DOM property, so the document arrives intact; the methods are on the exposed element.
 */
import { defineComponent, h, onMounted, ref } from 'vue'
import type { PropType } from 'vue'
import '@svgrid/enterprise/wc'

const PROP_NAMES = ["document","workbook","data","rows","columns","height","columnWidth","rowHeight","look","columnWidths","formats","extras","localization","commentAuthor","showRibbon","showFormulaBar","showTabs","showStatusBar"] as const
const EVENT_NAMES = ["action","ready","change"] as const

export type SvSheetProps = {
  document?: unknown
  workbook?: unknown
  data?: readonly unknown[]
  rows?: number
  columns?: number
  height?: number | "100%"
  columnWidth?: number
  rowHeight?: number
  look?: "excel" | "theme"
  columnWidths?: unknown
  formats?: unknown
  extras?: readonly unknown[]
  localization?: unknown
  commentAuthor?: string
  showRibbon?: boolean
  showFormulaBar?: boolean
  showTabs?: boolean
  showStatusBar?: boolean
}

export const SvSheet = defineComponent({
  name: 'SvSheet',
  props: Object.fromEntries(PROP_NAMES.map((n) => [n, { type: null as unknown as PropType<unknown>, required: false }])),
  emits: [...EVENT_NAMES],
  setup(props, { emit, expose }) {
    const host = ref<HTMLElement | null>(null)
    onMounted(() => {
      const el = host.value
      if (!el) return
      for (const name of EVENT_NAMES) el.addEventListener(name, (e) => emit(name, (e as CustomEvent).detail, e))
      const api = (el as HTMLElement & { api?: unknown; document?: unknown }).api
      if (api != null) emit('ready', { api, document: (el as HTMLElement & { document?: unknown }).document })
    })
    expose({
      get element() { return host.value as (HTMLElement & Record<string, unknown>) | null },
    })
    return () => {
      const attrs: Record<string, unknown> = { ref: host, style: { display: 'block' } }
      for (const name of PROP_NAMES) {
        const value = (props as Record<string, unknown>)[name]
        if (value !== undefined) attrs['.' + name] = value
      }
      return h('sv-sheet', attrs)
    }
  },
})

export default SvSheet
