/**
 * AUTO-GENERATED by scripts/generate-sheet-surface.mjs - DO NOT EDIT.
 * Regenerate: pnpm --filter @svgrid/enterprise generate:wc
 *
 * Declarations for the Vue wrapper.
 */
import type { DefineComponent } from 'vue'
export type SvSheetProps = {
  document?: unknown
  workbook?: unknown
  data?: readonly unknown[]
  gridSheets?: unknown
  rows?: number
  columns?: number
  height?: number | "100%"
  columnWidth?: number
  rowHeight?: number
  look?: "excel" | "theme"
  columnWidths?: unknown
  formats?: unknown
  extras?: readonly unknown[]
  localization?: unknown
  commentAuthor?: string
  showRibbon?: boolean
  showFormulaBar?: boolean
  showTabs?: boolean
  showStatusBar?: boolean
  presence?: readonly unknown[]
}
export declare const SvSheet: DefineComponent<SvSheetProps>
export default SvSheet
