/**
 * AUTO-GENERATED by scripts/generate-wrappers.mjs - DO NOT EDIT.
 * Regenerate: pnpm --filter @svgrid/grid-wc generate:wrappers
 *
 * Vue wrapper for <sv-chart>. Forwards every prop as a DOM property, so the spec object arrives intact.
 */
import { defineComponent, h, onMounted, ref } from 'vue'
import type { PropType } from 'vue'
import '@svgrid/grid-wc/chart'

const PROP_NAMES = ["spec","legend","interactive","dataLabels","formatValue","tooltipFormat","tooltipMode","tooltipPosition","tooltipSticky","zoomable","zoom","rangePresets","syncGroup","contextMenu","animate","live","drillable","drillPath","selectable","selected","hoverHighlight","announce","describe","localeText","crosshairLabels","brush","brushHeight","toolbar","width","height","autosize","annotatable","drawable"] as const
const EVENT_NAMES = ["select","drill","zoom","selectionchange","hover","annotate","annotationremove","drawingschange"] as const

export type SvChartProps = {
  spec?: unknown
  legend?: string
  interactive?: boolean
  dataLabels?: boolean
  formatValue?: unknown
  tooltipFormat?: unknown
  tooltipMode?: "shared" | "single"
  tooltipPosition?: "follow" | "top-left" | "top-right" | "bottom-left" | "bottom-right"
  tooltipSticky?: boolean
  zoomable?: boolean
  zoom?: unknown
  rangePresets?: boolean
  syncGroup?: string
  contextMenu?: boolean
  animate?: boolean
  live?: boolean
  drillable?: boolean
  drillPath?: readonly unknown[]
  selectable?: string
  selected?: readonly unknown[]
  hoverHighlight?: boolean
  announce?: boolean
  describe?: boolean
  localeText?: unknown
  crosshairLabels?: boolean
  brush?: boolean
  brushHeight?: number
  toolbar?: boolean
  width?: number
  height?: number
  autosize?: boolean
  annotatable?: boolean
  drawable?: boolean
}

/**
 * SvChart as a Vue component. Props are forwarded as DOM PROPERTIES through
 * the `.`-prefixed vnode key, Vue's own way of forcing a property assignment.
 */
export const SvChart = defineComponent({
  name: 'SvChart',
  props: {
    ...Object.fromEntries(PROP_NAMES.map((n) => [n, { type: null as unknown as PropType<unknown>, required: false }])),
  },
  emits: [...EVENT_NAMES],
  setup(props, { emit, expose }) {
    const host = ref<HTMLElement | null>(null)

    onMounted(() => {
      const el = host.value
      if (!el) return
      for (const name of EVENT_NAMES)
        el.addEventListener(name, (e) => emit(name, (e as CustomEvent).detail))
    })

    expose({
      get element() {
        return host.value
      },
    })

    return () => {
      const attrs: Record<string, unknown> = { ref: host, style: { display: 'block' } }
      for (const name of PROP_NAMES) {
        const value = (props as Record<string, unknown>)[name]
        if (value !== undefined) attrs['.' + name] = value
      }
      return h('sv-chart', attrs)
    }
  },
})

export default SvChart
