/**
 * AUTO-GENERATED by scripts/generate-wrappers.mjs - DO NOT EDIT.
 * Regenerate: pnpm --filter @svgrid/grid-wc generate:wrappers
 *
 * Vue wrapper. Removes the `isCustomElement` build config and the `.prop` modifier a raw custom element needs.
 */
import { defineComponent, h, onMounted, ref, watchEffect } from 'vue'
import type { PropType } from 'vue'
import '@svgrid/grid-wc'

const PROP_NAMES = ["data","columns","board","scheduler","chart","pivot","pivotMode","contextMenu","selectionBar","features","sortable","filterable","editable","treeData","groupable","groupBy","expanded","groupFooters","grandTotalRow","groupDisplayMode","autoGroupColumnHeader","autoGroupColumnWidth","pageable","loading","loadingOverlay","loadingSkeletonRows","error","emptyMessage","localization","showGlobalFilter","showColumnFilters","filterMode","showGroupingControls","showRowSelection","showPagination","pageSize","pageSizeOptions","paginationPosition","externalPagination","rowCount","pageIndex","virtualization","rowHeight","autoRowHeight","rowResize","headerHeight","overscan","containerHeight","columnVirtualization","columnOverscan","columnWidth","initialColumnPinning","fitColumns","columnResize","responsive","showFilterMenu","showFilterRow","enableCellSelection","moveCells","enableRowHover","copyHeadersToClipboard","processCellForClipboard","enableInlineEditing","fullRowEditing","enableRowSummaries","summary","statusBar","toolPanel","charting","columnMenuTabs","toolPanelDefaultOpen","toolPanelDefaultTab","selectionMode","showRowNumbers","zebraRows","rowNumberWidth","externalSort","initialSorting","initialAdvancedFilter","externalFilter","getRowId","rowClass","notes","editableComments","conditionalFormats","conditionalStatScope","isDetailRow","serverGroup","serverFilterValues","pinnedTopRows","pinnedBottomRows","enableColumnReorder","columnOrder","inferColumnTypes","rowDragManaged","rowDragGroup","alignedGridGroup","filterLocale"] as const
const EVENT_NAMES = ["pivotmodechange","expandedchange","paginationchange","apiready","rowselectionchange","cellselectionchange","sortingchange","advancedfilterchange","filterschange","notechange","cellvaluechange","activecellchange","cellclick","rowclick","celldoubleclick","rowdoubleclick","scrollbottomreached","columnorderchange","rowdragend","selectionchange"] as const

export type SvGridProps = {
  data?: readonly unknown[]
  columns?: readonly unknown[]
  board?: unknown
  scheduler?: unknown
  chart?: unknown
  pivot?: unknown
  pivotMode?: boolean
  contextMenu?: boolean
  selectionBar?: boolean
  features?: unknown
  sortable?: boolean
  filterable?: boolean
  editable?: boolean
  treeData?: unknown
  groupable?: boolean
  groupBy?: readonly unknown[]
  expanded?: unknown
  groupFooters?: boolean
  grandTotalRow?: boolean
  groupDisplayMode?: string
  autoGroupColumnHeader?: string
  autoGroupColumnWidth?: number
  pageable?: boolean
  loading?: boolean
  loadingOverlay?: boolean
  loadingSkeletonRows?: number
  error?: string | null
  emptyMessage?: string
  localization?: unknown
  showGlobalFilter?: boolean
  showColumnFilters?: boolean
  filterMode?: "row" | "menu" | "global" | "none"
  showGroupingControls?: boolean
  showRowSelection?: boolean
  showPagination?: boolean
  pageSize?: number
  pageSizeOptions?: readonly unknown[]
  paginationPosition?: "top" | "bottom" | "both"
  externalPagination?: boolean
  rowCount?: number
  pageIndex?: number
  virtualization?: boolean
  rowHeight?: number
  autoRowHeight?: boolean
  rowResize?: boolean
  headerHeight?: number
  overscan?: number
  containerHeight?: string
  columnVirtualization?: boolean
  columnOverscan?: number
  columnWidth?: number
  initialColumnPinning?: unknown
  fitColumns?: boolean
  columnResize?: boolean
  responsive?: boolean
  showFilterMenu?: boolean
  showFilterRow?: boolean
  enableCellSelection?: boolean
  moveCells?: boolean
  enableRowHover?: boolean
  copyHeadersToClipboard?: boolean
  processCellForClipboard?: unknown
  enableInlineEditing?: boolean
  fullRowEditing?: boolean
  enableRowSummaries?: boolean
  summary?: boolean
  statusBar?: boolean
  toolPanel?: boolean
  charting?: boolean
  columnMenuTabs?: boolean
  toolPanelDefaultOpen?: boolean
  toolPanelDefaultTab?: "columns" | "filters"
  selectionMode?: "row" | "cell" | "both" | "none"
  showRowNumbers?: boolean
  zebraRows?: boolean
  rowNumberWidth?: number
  externalSort?: boolean
  initialSorting?: readonly unknown[]
  initialAdvancedFilter?: unknown
  externalFilter?: boolean
  getRowId?: unknown
  rowClass?: unknown
  notes?: unknown
  editableComments?: boolean
  conditionalFormats?: readonly unknown[]
  conditionalStatScope?: "filtered" | "visible" | "all"
  isDetailRow?: unknown
  serverGroup?: unknown
  serverFilterValues?: unknown
  pinnedTopRows?: readonly unknown[]
  pinnedBottomRows?: readonly unknown[]
  enableColumnReorder?: boolean
  columnOrder?: readonly unknown[]
  inferColumnTypes?: boolean
  rowDragManaged?: boolean
  rowDragGroup?: string
  alignedGridGroup?: string
  filterLocale?: string
  shadow?: boolean
}

/**
 * SvGrid as a Vue component.
 *
 * Props are declared loosely (`null` type) and forwarded as DOM PROPERTIES
 * through the `.`-prefixed vnode key, which is Vue's own way of forcing a
 * property assignment - the same thing `:columns.prop` does in a template,
 * applied to all 98 of them so a consumer never has to think about it.
 */
export const SvGrid = defineComponent({
  name: 'SvGrid',
  props: {
    ...Object.fromEntries(PROP_NAMES.map((n) => [n, { type: null as unknown as PropType<unknown>, required: false }])),
    shadow: { type: Boolean, default: false },
  },
  emits: [...EVENT_NAMES],
  setup(props, { emit, expose }) {
    const host = ref<HTMLElement | null>(null)

    watchEffect(() => {
      if (props.shadow) void import('@svgrid/grid-wc/shadow')
    })

    onMounted(() => {
      const el = host.value
      if (!el) return
      for (const name of EVENT_NAMES)
        el.addEventListener(name, (e) => emit(name, (e as CustomEvent).detail))

      // `apiready` fires once, during the element's own mount, so a listener
      // bound here can miss it. The element parks the handle for that reason.
      const api = (el as HTMLElement & { api?: unknown }).api
      if (api != null) emit('apiready', api)
    })

    expose({
      get element() {
        return host.value
      },
      get api() {
        return (host.value as (HTMLElement & { api?: unknown }) | null)?.api ?? null
      },
    })

    return () => {
      const attrs: Record<string, unknown> = { ref: host, style: { display: 'block', height: '100%' } }
      for (const name of PROP_NAMES) {
        const value = (props as Record<string, unknown>)[name]
        // A leading '.' forces a DOM property assignment in Vue's runtime-dom,
        // which is what arrays and objects need.
        if (value !== undefined) attrs['.' + name] = value
      }
      return h(props.shadow ? 'sv-grid-shadow' : 'sv-grid', attrs)
    }
  },
})

export default SvGrid
