/**
 * AUTO-GENERATED by scripts/generate-wrappers.mjs - DO NOT EDIT.
 * Regenerate: pnpm --filter @svgrid/grid-wc generate:wrappers
 *
 * React wrapper for <sv-chart>. Assigns object props (the spec above all) as properties, which React <=18 would otherwise stringify onto attributes.
 */
import { createElement, forwardRef, useEffect, useImperativeHandle, useRef } from 'react'
import type { Ref } from 'react'
import '@svgrid/grid-wc/chart'

export interface SvChartProps {
  /** `property only` - ChartSpec */
  spec?: unknown
  /** `legend` - boolean | ChartLegendPosition */
  legend?: string
  /** `interactive` - boolean */
  interactive?: boolean
  /** `data-labels` - boolean | ChartDataLabelConfig */
  dataLabels?: boolean
  /** `property only` - (value: number) => string */
  formatValue?: unknown
  /** `property only` - (ctx: ChartTooltipContext) => { title?: string; rows?: ChartTooltipRow[] } */
  tooltipFormat?: unknown
  /** `tooltip-mode` - 'shared' | 'single' */
  tooltipMode?: "shared" | "single"
  /** `tooltip-position` - 'follow' | 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right' */
  tooltipPosition?: "follow" | "top-left" | "top-right" | "bottom-left" | "bottom-right"
  /** `tooltip-sticky` - boolean */
  tooltipSticky?: boolean
  /** `zoomable` - boolean | ChartZoomConfig */
  zoomable?: boolean
  /** `property only` - ChartZoomWindow | null */
  zoom?: unknown
  /** `range-presets` - boolean | ChartRangePreset[] */
  rangePresets?: boolean
  /** `sync-group` - string */
  syncGroup?: string
  /** `context-menu` - boolean | MenuItem[] | ((target: ChartContextTarget) => MenuItem[]) */
  contextMenu?: boolean
  /** `animate` - boolean | ChartAnimateConfig */
  animate?: boolean
  /** `live` - boolean */
  live?: boolean
  /** `drillable` - boolean */
  drillable?: boolean
  /** `property only` - string[] */
  drillPath?: readonly unknown[]
  /** `selectable` - boolean | 'single' | 'multi' */
  selectable?: string
  /** `property only` - ChartPointRef[] */
  selected?: readonly unknown[]
  /** `hover-highlight` - boolean */
  hoverHighlight?: boolean
  /** `announce` - boolean */
  announce?: boolean
  /** `describe` - boolean */
  describe?: boolean
  /** `property only` - Partial<ChartMessages> */
  localeText?: unknown
  /** `crosshair-labels` - boolean */
  crosshairLabels?: boolean
  /** `brush` - boolean */
  brush?: boolean
  /** `brush-height` - number */
  brushHeight?: number
  /** `toolbar` - boolean */
  toolbar?: boolean
  /** `width` - number */
  width?: number
  /** `height` - number */
  height?: number
  /** `autosize` - boolean */
  autosize?: boolean
  /** `annotatable` - boolean */
  annotatable?: boolean
  /** `drawable` - boolean | ChartDrawingKind[] */
  drawable?: boolean

  /** `select` */
  onSelect?: (detail: unknown) => void
  /** `drill` */
  onDrill?: (detail: unknown) => void
  /** `zoom` */
  onZoom?: (detail: unknown) => void
  /** `selectionchange` */
  onSelectionChange?: (detail: unknown) => void
  /** `hover` */
  onHover?: (detail: unknown) => void
  /** `annotate` */
  onAnnotate?: (detail: unknown) => void
  /** `annotationremove` */
  onAnnotationRemove?: (detail: number) => void
  /** `drawingschange` */
  onDrawingsChange?: (detail: unknown) => void

  /** Forwarded to the host element. */
  className?: string
  style?: Record<string, string | number>
}

/** The host element, reachable through a ref. */
export interface SvChartHandle {
  element: HTMLElement | null
}

const PROP_NAMES = ["spec","legend","interactive","dataLabels","formatValue","tooltipFormat","tooltipMode","tooltipPosition","tooltipSticky","zoomable","zoom","rangePresets","syncGroup","contextMenu","animate","live","drillable","drillPath","selectable","selected","hoverHighlight","announce","describe","localeText","crosshairLabels","brush","brushHeight","toolbar","width","height","autosize","annotatable","drawable"] as const

const EVENTS: Array<[handler: string, event: string]> = [["onSelect","select"],["onDrill","drill"],["onZoom","zoom"],["onSelectionChange","selectionchange"],["onHover","hover"],["onAnnotate","annotate"],["onAnnotationRemove","annotationremove"],["onDrawingsChange","drawingschange"]]

/**
 * SvChart as a React component. Same shape as the grid wrapper: props are
 * written as DOM properties when they change, handlers are bound once through
 * a ref so inline arrows do not rebind on every render.
 */
export const SvChart = forwardRef(function SvChart(props: SvChartProps, ref: Ref<SvChartHandle>) {
  const hostRef = useRef<HTMLElement | null>(null)
  const { className, style, ...rest } = props

  const written = useRef<Record<string, unknown>>({})
  useEffect(() => {
    const el = hostRef.current as unknown as Record<string, unknown> | null
    if (!el) return
    for (const name of PROP_NAMES) {
      const value = (rest as Record<string, unknown>)[name]
      if (value === undefined || Object.is(written.current[name], value)) continue
      written.current[name] = value
      el[name] = value
    }
  })

  const handlers = useRef(rest as Record<string, unknown>)
  handlers.current = rest as Record<string, unknown>

  useEffect(() => {
    const el = hostRef.current
    if (!el) return
    const bound: Array<[string, EventListener]> = []
    for (const [handler, event] of EVENTS) {
      const listener: EventListener = (e) => {
        const fn = handlers.current[handler] as ((detail: unknown) => void) | undefined
        fn?.((e as CustomEvent).detail)
      }
      el.addEventListener(event, listener)
      bound.push([event, listener])
    }
    return () => {
      for (const [event, listener] of bound) el.removeEventListener(event, listener)
    }
  }, [])

  useImperativeHandle(
    ref,
    () => ({
      get element() {
        return hostRef.current
      },
    }),
    [],
  )

  return createElement('sv-chart', {
    ref: hostRef,
    class: className,
    style: { display: 'block', ...style },
  })
})

export default SvChart
