/**
 * AUTO-GENERATED by scripts/generate-wrappers.mjs - DO NOT EDIT.
 * Regenerate: pnpm --filter @svgrid/grid-wc generate:wrappers
 *
 * React wrapper. React <=18 assigns object props to ATTRIBUTES, which turns `columns` into "[object Object]"; this assigns them as properties instead.
 */
import { createElement, forwardRef, useEffect, useImperativeHandle, useRef } from 'react'
import type { Ref } from 'react'
import '@svgrid/grid-wc'

export interface SvGridProps {
  /** `property only` - ReadonlyArray<TData> */
  data?: readonly unknown[]
  /** `property only` - Array<ColumnDef<TFeatures, TData>> */
  columns?: readonly unknown[]
  /** `property only` - BoardConfig<TFeatures, TData> */
  board?: unknown
  /** `property only` - SchedulerConfig<TFeatures, TData> */
  scheduler?: unknown
  /** `property only` - ChartViewConfig<TFeatures, TData> */
  chart?: unknown
  /** `property only` - GridPivotConfig<TData> */
  pivot?: unknown
  /** `pivot-mode` - boolean */
  pivotMode?: boolean
  /** `context-menu` - boolean | ReadonlyArray<ContextMenuItem<TData>> */
  contextMenu?: boolean
  /** `selection-bar` - | boolean | ReadonlyArray<SelectionBarAction<TData> | SelectionBarBuiltin> | SelectionBarC */
  selectionBar?: boolean
  /** `property only` - TFeatures */
  features?: unknown
  /** `sortable` - boolean */
  sortable?: boolean
  /** `filterable` - boolean */
  filterable?: boolean
  /** `editable` - boolean */
  editable?: boolean
  /** `property only` - { parentField: string; idField?: string; column?: string; indentPx?: number; } */
  treeData?: unknown
  /** `groupable` - boolean */
  groupable?: boolean
  /** `property only` - ReadonlyArray<string> */
  groupBy?: readonly unknown[]
  /** `property only` - Record<string, boolean> */
  expanded?: unknown
  /** `group-footers` - boolean */
  groupFooters?: boolean
  /** `grand-total-row` - boolean */
  grandTotalRow?: boolean
  /** `group-display-mode` - GroupDisplayType */
  groupDisplayMode?: string
  /** `auto-group-column-header` - string */
  autoGroupColumnHeader?: string
  /** `auto-group-column-width` - number */
  autoGroupColumnWidth?: number
  /** `pageable` - boolean */
  pageable?: boolean
  /** `loading` - boolean */
  loading?: boolean
  /** `loading-overlay` - boolean */
  loadingOverlay?: boolean
  /** `loading-skeleton-rows` - number */
  loadingSkeletonRows?: number
  /** `error` - string | null */
  error?: string | null
  /** `empty-message` - string */
  emptyMessage?: string
  /** `property only` - GridLocalization */
  localization?: unknown
  /** `show-global-filter` - boolean */
  showGlobalFilter?: boolean
  /** `show-column-filters` - boolean */
  showColumnFilters?: boolean
  /** `filter-mode` - "row" | "menu" | "global" | "none" */
  filterMode?: "row" | "menu" | "global" | "none"
  /** `show-grouping-controls` - boolean */
  showGroupingControls?: boolean
  /** `show-row-selection` - boolean */
  showRowSelection?: boolean
  /** `show-pagination` - boolean */
  showPagination?: boolean
  /** `page-size` - number */
  pageSize?: number
  /** `property only` - number[] */
  pageSizeOptions?: readonly unknown[]
  /** `pagination-position` - 'top' | 'bottom' | 'both' */
  paginationPosition?: "top" | "bottom" | "both"
  /** `external-pagination` - boolean */
  externalPagination?: boolean
  /** `row-count` - number */
  rowCount?: number
  /** `page-index` - number */
  pageIndex?: number
  /** `virtualization` - boolean */
  virtualization?: boolean
  /** `row-height` - number | ((rowIndex: number) => number) */
  rowHeight?: number
  /** `auto-row-height` - boolean */
  autoRowHeight?: boolean
  /** `row-resize` - boolean */
  rowResize?: boolean
  /** `header-height` - number */
  headerHeight?: number
  /** `overscan` - number */
  overscan?: number
  /** `container-height` - number | string */
  containerHeight?: string
  /** `column-virtualization` - boolean */
  columnVirtualization?: boolean
  /** `column-overscan` - number */
  columnOverscan?: number
  /** `column-width` - number */
  columnWidth?: number
  /** `property only` - { left?: ReadonlyArray<string>; right?: ReadonlyArray<string>; } */
  initialColumnPinning?: unknown
  /** `fit-columns` - boolean */
  fitColumns?: boolean
  /** `column-resize` - boolean */
  columnResize?: boolean
  /** `responsive` - boolean | { breakpoint?: number } */
  responsive?: boolean
  /** `show-filter-menu` - boolean */
  showFilterMenu?: boolean
  /** `show-filter-row` - boolean */
  showFilterRow?: boolean
  /** `enable-cell-selection` - boolean */
  enableCellSelection?: boolean
  /** `move-cells` - boolean */
  moveCells?: boolean
  /** `enable-row-hover` - boolean */
  enableRowHover?: boolean
  /** `copy-headers-to-clipboard` - boolean */
  copyHeadersToClipboard?: boolean
  /** `property only` - (params: { value: unknown; column: unknown; row: TData; rowIndex: number; columnId: string */
  processCellForClipboard?: unknown
  /** `enable-inline-editing` - boolean */
  enableInlineEditing?: boolean
  /** `full-row-editing` - boolean */
  fullRowEditing?: boolean
  /** `enable-row-summaries` - boolean */
  enableRowSummaries?: boolean
  /** `summary` - boolean */
  summary?: boolean
  /** `status-bar` - | boolean | { aggregates?: ReadonlyArray< "count" | "numericCount" | "sum" | "avg" | "min" */
  statusBar?: boolean
  /** `tool-panel` - boolean */
  toolPanel?: boolean
  /** `charting` - boolean | ChartingConfig<TData> */
  charting?: boolean
  /** `column-menu-tabs` - boolean */
  columnMenuTabs?: boolean
  /** `tool-panel-default-open` - boolean */
  toolPanelDefaultOpen?: boolean
  /** `tool-panel-default-tab` - "columns" | "filters" */
  toolPanelDefaultTab?: "columns" | "filters"
  /** `selection-mode` - "row" | "cell" | "both" | "none" */
  selectionMode?: "row" | "cell" | "both" | "none"
  /** `show-row-numbers` - boolean */
  showRowNumbers?: boolean
  /** `zebra-rows` - boolean */
  zebraRows?: boolean
  /** `row-number-width` - number */
  rowNumberWidth?: number
  /** `external-sort` - boolean */
  externalSort?: boolean
  /** `property only` - Array<{ id: string; desc: boolean }> */
  initialSorting?: readonly unknown[]
  /** `property only` - GridPredicateExpr | null */
  initialAdvancedFilter?: unknown
  /** `external-filter` - boolean */
  externalFilter?: boolean
  /** `property only` - (row: TData, index: number) => string */
  getRowId?: unknown
  /** `property only` - (ctx: { row: TData; rowIndex: number; }) => string | ReadonlyArray<string> | Record<string */
  rowClass?: unknown
  /** `property only` - Record<string, Record<string, string>> */
  notes?: unknown
  /** `editable-comments` - boolean */
  editableComments?: boolean
  /** `property only` - ReadonlyArray<ConditionalFormat<TData>> */
  conditionalFormats?: readonly unknown[]
  /** `conditional-stat-scope` - "filtered" | "visible" | "all" */
  conditionalStatScope?: "filtered" | "visible" | "all"
  /** `property only` - (row: TData, rowIndex: number) => boolean */
  isDetailRow?: unknown
  /** `property only` - { isGroup: (row: TData) => boolean; level: (row: TData) => number; expanded?: (row: TData) */
  serverGroup?: unknown
  /** `property only` - (columnId: string) => Promise<string[]> */
  serverFilterValues?: unknown
  /** `property only` - ReadonlyArray<TData> */
  pinnedTopRows?: readonly unknown[]
  /** `property only` - ReadonlyArray<TData> */
  pinnedBottomRows?: readonly unknown[]
  /** `enable-column-reorder` - boolean */
  enableColumnReorder?: boolean
  /** `property only` - ReadonlyArray<string> */
  columnOrder?: readonly unknown[]
  /** `infer-column-types` - boolean */
  inferColumnTypes?: boolean
  /** `row-drag-managed` - boolean */
  rowDragManaged?: boolean
  /** `row-drag-group` - string */
  rowDragGroup?: string
  /** `aligned-grid-group` - string */
  alignedGridGroup?: string
  /** `filter-locale` - string | ReadonlyArray<string> */
  filterLocale?: string

  /** `pivotmodechange` */
  onPivotModeChange?: (detail: boolean) => void
  /** `expandedchange` */
  onExpandedChange?: (detail: Record<string, boolean>) => void
  /** `paginationchange` */
  onPaginationChange?: (detail: { pageIndex: number; pageSize: number }) => void
  /** `apiready` */
  onApiReady?: (detail: unknown) => void
  /** `rowselectionchange` */
  onRowSelectionChange?: (detail: { selection: Record<string, boolean>; rows: Record<string, unknown>[] }) => void
  /** `cellselectionchange` */
  onCellSelectionChange?: (detail: Array<[number, number, number, number]>) => void
  /** `sortingchange` */
  onSortingChange?: (detail: Array<{ id: string; desc: boolean }>) => void
  /** `advancedfilterchange` */
  onAdvancedFilterChange?: (detail: unknown) => void
  /** `filterschange` */
  onFiltersChange?: (detail: unknown) => void
  /** `notechange` */
  onNoteChange?: (detail: { rowId: string; columnId: string; note: string }) => void
  /** `cellvaluechange` */
  onCellValueChange?: (detail: { rowIndex: number; columnId: string; oldValue: unknown; newValue: unknown; row: Record<string, unknown>; }) => void
  /** `activecellchange` */
  onActiveCellChange?: (detail: { rowIndex: number; colIndex: number; columnId: string; }) => void
  /** `cellclick` */
  onCellClick?: (detail: { rowIndex: number; colIndex: number; columnId: string; value: unknown; row: Record<string, unknown>; }) => void
  /** `rowclick` */
  onRowClick?: (detail: { rowIndex: number; columnId: string; row: Record<string, unknown>; }) => void
  /** `celldoubleclick` */
  onCellDoubleClick?: (detail: { rowIndex: number; colIndex: number; columnId: string; value: unknown; row: Record<string, unknown>; }) => void
  /** `rowdoubleclick` */
  onRowDoubleClick?: (detail: { rowIndex: number; columnId: string; row: Record<string, unknown>; }) => void
  /** `scrollbottomreached` */
  onScrollBottomReached?: (detail: { scrollTop: number; scrollHeight: number; clientHeight: number; }) => void
  /** `columnorderchange` */
  onColumnOrderChange?: (detail: ReadonlyArray<string>) => void
  /** `rowdragend` */
  onRowDragEnd?: (detail: { row: Record<string, unknown>; toIndex: number; sameGrid: boolean; fromGridId: number; toGridId: number; }) => void
  /** `selectionchange` - published alias of rowselectionchange, detail is the selected rows */
  onSelectionchange?: (detail: unknown) => void

  /** Render inside an open shadow root, so page CSS cannot reach the grid. */
  shadow?: boolean
  /** Forwarded to the host element. */
  className?: string
  style?: Record<string, string | number>
}

/** The grid's imperative api, reachable through a ref. */
export interface SvGridHandle {
  /** The host custom element. */
  element: HTMLElement | null
  /** The grid api, once `apiready` has fired. */
  api: unknown
}

const PROP_NAMES = ["data","columns","board","scheduler","chart","pivot","pivotMode","contextMenu","selectionBar","features","sortable","filterable","editable","treeData","groupable","groupBy","expanded","groupFooters","grandTotalRow","groupDisplayMode","autoGroupColumnHeader","autoGroupColumnWidth","pageable","loading","loadingOverlay","loadingSkeletonRows","error","emptyMessage","localization","showGlobalFilter","showColumnFilters","filterMode","showGroupingControls","showRowSelection","showPagination","pageSize","pageSizeOptions","paginationPosition","externalPagination","rowCount","pageIndex","virtualization","rowHeight","autoRowHeight","rowResize","headerHeight","overscan","containerHeight","columnVirtualization","columnOverscan","columnWidth","initialColumnPinning","fitColumns","columnResize","responsive","showFilterMenu","showFilterRow","enableCellSelection","moveCells","enableRowHover","copyHeadersToClipboard","processCellForClipboard","enableInlineEditing","fullRowEditing","enableRowSummaries","summary","statusBar","toolPanel","charting","columnMenuTabs","toolPanelDefaultOpen","toolPanelDefaultTab","selectionMode","showRowNumbers","zebraRows","rowNumberWidth","externalSort","initialSorting","initialAdvancedFilter","externalFilter","getRowId","rowClass","notes","editableComments","conditionalFormats","conditionalStatScope","isDetailRow","serverGroup","serverFilterValues","pinnedTopRows","pinnedBottomRows","enableColumnReorder","columnOrder","inferColumnTypes","rowDragManaged","rowDragGroup","alignedGridGroup","filterLocale"] as const

const EVENTS: Array<[handler: string, event: string]> = [["onPivotModeChange","pivotmodechange"],["onExpandedChange","expandedchange"],["onPaginationChange","paginationchange"],["onApiReady","apiready"],["onRowSelectionChange","rowselectionchange"],["onCellSelectionChange","cellselectionchange"],["onSortingChange","sortingchange"],["onAdvancedFilterChange","advancedfilterchange"],["onFiltersChange","filterschange"],["onNoteChange","notechange"],["onCellValueChange","cellvaluechange"],["onActiveCellChange","activecellchange"],["onCellClick","cellclick"],["onRowClick","rowclick"],["onCellDoubleClick","celldoubleclick"],["onRowDoubleClick","rowdoubleclick"],["onScrollBottomReached","scrollbottomreached"],["onColumnOrderChange","columnorderchange"],["onRowDragEnd","rowdragend"],["onSelectionchange","selectionchange"]]

/**
 * SvGrid as a React component.
 *
 * Every non-primitive prop is assigned as a DOM property in an effect rather
 * than passed through JSX, because React 18 and earlier stringify them onto
 * attributes and an attribute cannot hold an array.
 */
export const SvGrid = forwardRef(function SvGrid(props: SvGridProps, ref: Ref<SvGridHandle>) {
  const hostRef = useRef<HTMLElement | null>(null)
  const { shadow, className, style, ...rest } = props

  // The shadow element is a separate bundle; only pay for it when asked.
  useEffect(() => {
    if (shadow) void import('@svgrid/grid-wc/shadow')
  }, [shadow])

  // Assign only what CHANGED. This effect has no dependency array - 98 props
  // cannot be listed, and listing a subset would silently miss the rest - so it
  // runs on every render, and writing all 98 each time would hand the grid 98
  // fresh values per keystroke of parent state. Comparing first also stops the
  // wrapper clobbering a value the grid maintains itself.
  const written = useRef<Record<string, unknown>>({})
  useEffect(() => {
    const el = hostRef.current as (HTMLElement & Record<string, unknown>) | null
    if (!el) return
    for (const name of PROP_NAMES) {
      const value = (rest as Record<string, unknown>)[name]
      if (value === undefined || Object.is(written.current[name], value)) continue
      written.current[name] = value
      el[name] = value
    }
  })

  // Handlers go through a ref so the listeners can be bound ONCE. Binding them
  // per render - which is what an effect with no deps does - would add and
  // remove 20 listeners on every parent state change, and inline arrow handlers
  // (the normal way to write them) change identity every render, so a deps
  // array on the handlers themselves would not help either.
  const handlers = useRef(rest as Record<string, unknown>)
  handlers.current = rest as Record<string, unknown>

  useEffect(() => {
    const el = hostRef.current
    if (!el) return
    const bound: Array<[string, EventListener]> = []
    for (const [handler, event] of EVENTS) {
      const listener: EventListener = (e) => {
        const fn = handlers.current[handler] as ((detail: unknown) => void) | undefined
        fn?.((e as CustomEvent).detail)
      }
      el.addEventListener(event, listener)
      bound.push([event, listener])
    }

    // `apiready` fires ONCE, during the element's own mount - which is before
    // React can bind anything, so the handler would simply never run. The
    // element parks the handle on itself for exactly this reason, so replay it.
    // (Vue happens to bind early enough to win that race; relying on the order
    // would be luck, so all three wrappers replay.)
    const onReady = handlers.current.onApiReady as ((detail: unknown) => void) | undefined
    const api = (el as HTMLElement & { api?: unknown }).api
    if (onReady && api != null) onReady(api)

    return () => {
      for (const [event, listener] of bound) el.removeEventListener(event, listener)
    }
  }, [])

  useImperativeHandle(
    ref,
    () => ({
      get element() {
        return hostRef.current
      },
      get api() {
        return (hostRef.current as (HTMLElement & { api?: unknown }) | null)?.api ?? null
      },
    }),
    [],
  )

  return createElement(shadow ? 'sv-grid-shadow' : 'sv-grid', {
    ref: hostRef,
    class: className,
    style: { display: 'block', height: '100%', ...style },
  })
})

export default SvGrid
