#!/usr/bin/env node
/**
 * Build plugins/svgrid/ - the Claude Code plugin - from the canonical sources.
 *
 * Why a copy rather than the repo root as the plugin: installing a plugin
 * copies its whole directory into the plugin cache. Pointing at the repo root
 * drags node_modules along, which on Windows fails outright on pnpm's symlinks
 * ("EPERM: operation not permitted, symlink ... .pnpm/@electric-sql+pglite").
 * The plugin directory has to be small and self-contained.
 *
 * Why not move the skill here instead: `skills/svgrid/` is the documented
 * location, linked from AGENTS.md, docs/help/skill.md and the changelog. It
 * stays canonical; this script mirrors it, and tools/plugin-sync.test.ts fails
 * if the mirror drifts.
 *
 *   node tools/sync-plugin.mjs           write the plugin directory
 *   node tools/sync-plugin.mjs --check   fail if it is out of date (CI)
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync, statSync, rmSync, existsSync } from 'node:fs'
import { join, dirname, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const SKILL_SRC = join(ROOT, 'skills', 'svgrid')
const PLUGIN_DIR = join(ROOT, 'plugins', 'svgrid')
const SKILL_DEST = join(PLUGIN_DIR, 'skills', 'svgrid')
const check = process.argv.includes('--check')

/** The MCP package version is the plugin's version: they ship as one thing. */
const mcpPkg = JSON.parse(readFileSync(join(ROOT, 'packages', 'mcp', 'package.json'), 'utf8'))

const manifest = {
  name: 'svgrid',
  version: mcpPkg.version,
  description:
    'Write SvGrid code that runs: the house-style skill plus the MCP server that checks every file against the real API surface before you see it.',
  author: { name: 'jQWidgets', email: 'sales@jqwidgets.com', url: 'https://svgrid.com' },
  homepage: 'https://svgrid.com/docs/help/mcp-server/',
  repository: 'https://github.com/sv-grid/sv-grid',
  license: 'MIT',
  keywords: [
    'svelte',
    'svelte5',
    'sveltekit',
    'data grid',
    'datagrid',
    'data table',
    'svgrid',
    'mcp',
    'code verification',
  ],
  // The hosted server, so the plugin works with no Node and no install. Six
  // tools instead of the stdio server's 36; swapping to `npx @svgrid/mcp`
  // trades that for the Svelte compiler pass and the Studio tools.
  mcpServers: {
    svgrid: { type: 'http', url: 'https://mcp.svgrid.com/mcp' },
  },
}

/** Every file under `dir`, as paths relative to it. */
function walk(dir, base = dir, out = []) {
  for (const entry of readdirSync(dir).sort()) {
    const p = join(dir, entry)
    if (statSync(p).isDirectory()) walk(p, base, out)
    else out.push(relative(base, p).replaceAll('\\', '/'))
  }
  return out
}

const REPO_URL = 'https://github.com/sv-grid/sv-grid/tree/main'

/**
 * Links like `](../../packages/mcp)` resolve from skills/svgrid/ but not from
 * plugins/svgrid/skills/svgrid/ - and once the plugin is installed under
 * ~/.claude/plugins/, a relative path into this repo means nothing at all.
 * Rewrite anything that escapes the skill directory to a GitHub URL; leave
 * `./rules/*.md` alone, since those travel with the copy.
 */
function absolutizeRepoLinks(text, relDepth) {
  return text.replace(/\]\((\.\.\/[^)]*)\)/g, (whole, target) => {
    const parts = target.split('/')
    let up = 0
    while (parts[0] === '..') {
      parts.shift()
      up++
    }
    // Only rewrite links that climb out of the skill folder itself.
    if (up <= relDepth) return whole
    return `](${REPO_URL}/${parts.join('/')})`
  })
}

const files = walk(SKILL_SRC)
const wanted = new Map()
for (const rel of files) {
  const depth = rel.split('/').length - 1
  const body = readFileSync(join(SKILL_SRC, rel))
  wanted.set(
    join('skills', 'svgrid', rel),
    rel.endsWith('.md') ? Buffer.from(absolutizeRepoLinks(body.toString('utf8'), depth)) : body,
  )
}
wanted.set(join('.claude-plugin', 'plugin.json'), Buffer.from(JSON.stringify(manifest, null, 2) + '\n'))
wanted.set(
  'README.md',
  Buffer.from(
    [
      '# SvGrid plugin for Claude Code',
      '',
      '**Generated by `tools/sync-plugin.mjs` - do not edit by hand.** The skill is',
      'mirrored from `skills/svgrid/`; edit it there and re-run the script.',
      '',
      '```',
      '/plugin marketplace add sv-grid/sv-grid',
      '/plugin install svgrid@svgrid',
      '```',
      '',
      'Installs two things together:',
      '',
      '- the **svgrid skill**, which carries the house style - column shapes, the',
      '  `--sg-*` theming convention, which package a symbol lives in;',
      '- the **MCP server** at `https://mcp.svgrid.com/mcp`, whose',
      '  `check_svgrid_code` tool validates every file against the real exported',
      '  surface of the installed version before you ever see the code.',
      '',
      'The hosted server needs no Node and no key. For the Svelte compiler pass and',
      'the 27 Studio tools, point the server at `npx @svgrid/mcp` instead - see',
      '<https://svgrid.com/docs/help/mcp-server/>.',
      '',
    ].join('\n'),
  ),
)

// Compare before writing so --check can report without touching anything.
const existing = existsSync(PLUGIN_DIR) ? walk(PLUGIN_DIR) : []
const wantedPaths = new Set([...wanted.keys()].map((k) => k.replaceAll('\\', '/')))
const drift = []
for (const [rel, buf] of wanted) {
  const dest = join(PLUGIN_DIR, rel)
  if (!existsSync(dest) || !readFileSync(dest).equals(buf)) drift.push(rel.replaceAll('\\', '/'))
}
for (const rel of existing) {
  if (!wantedPaths.has(rel)) drift.push(`${rel} (stale)`)
}

if (check) {
  if (drift.length) {
    console.error('sync-plugin: plugins/svgrid is out of date:\n  ' + drift.join('\n  '))
    console.error('\nRun `node tools/sync-plugin.mjs` and commit the result.')
    process.exit(1)
  }
  console.log('sync-plugin: plugins/svgrid is up to date')
  process.exit(0)
}

rmSync(PLUGIN_DIR, { recursive: true, force: true })
for (const [rel, buf] of wanted) {
  const dest = join(PLUGIN_DIR, rel)
  mkdirSync(dirname(dest), { recursive: true })
  writeFileSync(dest, buf)
}
console.log(`sync-plugin: wrote plugins/svgrid (${wanted.size} files, v${manifest.version})`)
