/**
 * AUTO-GENERATED by scripts/generate-wrappers.mjs - DO NOT EDIT.
 * Regenerate: pnpm --filter @svgrid/grid-wc generate:wrappers
 *
 * Angular entry point.
 */
export { SvGridComponent } from './svgrid.component'
