/**
 * AUTO-GENERATED by scripts/generate-wrappers.mjs - DO NOT EDIT.
 * Regenerate: pnpm --filter @svgrid/grid-wc generate:wrappers
 *
 * Angular wrapper for <sv-chart>. Binds @Input / @Output straight onto the custom element, which IS this component's host.
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
import {
  Component,
  ElementRef,
  EventEmitter,
  Input,
  OnChanges,
  OnDestroy,
  OnInit,
  Output,
  SimpleChanges,
} from '@angular/core'
import '@svgrid/grid-wc/chart'

const PROP_NAMES: string[] = ["spec","legend","interactive","dataLabels","formatValue","tooltipFormat","tooltipMode","tooltipPosition","tooltipSticky","zoomable","zoom","rangePresets","syncGroup","contextMenu","animate","live","drillable","drillPath","selectable","selected","hoverHighlight","announce","describe","localeText","crosshairLabels","brush","brushHeight","toolbar","width","height","autosize","annotatable","drawable"]
/** DOM event -> output name (`zoom` -> `zoomChange`, the two-way convention). */
const EVENTS: Array<[string, string]> = [["select","select"],["drill","drill"],["zoom","zoomChange"],["selectionchange","selectionchange"],["hover","hover"],["annotate","annotate"],["annotationremove","annotationremove"],["drawingschange","drawingschange"]]

/**
 * SvChart as an Angular component. The selector is the custom element's own
 * tag and the component has no template: its host IS the `<sv-chart>` the
 * browser upgrades, exactly like the grid wrapper.
 */
@Component({
  selector: 'sv-chart',
  standalone: true,
  template: '',
})
export class SvChartComponent implements OnInit, OnChanges, OnDestroy {
  @Input() spec?: unknown
  @Input() legend?: string
  @Input() interactive?: boolean
  @Input() dataLabels?: boolean
  @Input() formatValue?: unknown
  @Input() tooltipFormat?: unknown
  @Input() tooltipMode?: "shared" | "single"
  @Input() tooltipPosition?: "follow" | "top-left" | "top-right" | "bottom-left" | "bottom-right"
  @Input() tooltipSticky?: boolean
  @Input() zoomable?: boolean
  @Input() zoom?: unknown
  @Input() rangePresets?: boolean
  @Input() syncGroup?: string
  @Input() contextMenu?: boolean
  @Input() animate?: boolean
  @Input() live?: boolean
  @Input() drillable?: boolean
  @Input() drillPath?: readonly unknown[]
  @Input() selectable?: string
  @Input() selected?: readonly unknown[]
  @Input() hoverHighlight?: boolean
  @Input() announce?: boolean
  @Input() describe?: boolean
  @Input() localeText?: unknown
  @Input() crosshairLabels?: boolean
  @Input() brush?: boolean
  @Input() brushHeight?: number
  @Input() toolbar?: boolean
  @Input() width?: number
  @Input() height?: number
  @Input() autosize?: boolean
  @Input() annotatable?: boolean
  @Input() drawable?: boolean

  @Output() select = new EventEmitter<unknown>()
  @Output() drill = new EventEmitter<unknown>()
  @Output() zoomChange = new EventEmitter<unknown>()
  @Output() selectionchange = new EventEmitter<unknown>()
  @Output() hover = new EventEmitter<unknown>()
  @Output() annotate = new EventEmitter<unknown>()
  @Output() annotationremove = new EventEmitter<unknown>()
  @Output() drawingschange = new EventEmitter<unknown>()

  private listeners: Array<[string, EventListener]> = []

  constructor(private readonly elementRef: ElementRef<HTMLElement>) {}

  ngOnInit(): void {
    const el = this.elementRef.nativeElement
    for (const [name, output] of EVENTS) {
      const listener: EventListener = (e) =>
        (this as any)[output]?.emit((e as CustomEvent).detail)
      el.addEventListener(name, listener)
      this.listeners.push([name, listener])
    }
    this.sync(PROP_NAMES)
  }

  ngOnChanges(changes: SimpleChanges): void {
    this.sync(Object.keys(changes).filter((k) => PROP_NAMES.includes(k)))
  }

  ngOnDestroy(): void {
    const el = this.elementRef.nativeElement
    for (const [name, listener] of this.listeners) el.removeEventListener(name, listener)
    this.listeners = []
  }

  /** Assign as DOM PROPERTIES - an attribute is a string, and the spec is not. */
  private sync(names: string[]): void {
    const el = this.elementRef.nativeElement as unknown as Record<string, unknown>
    for (const name of names) {
      const value = (this as any)[name]
      if (value !== undefined) el[name] = value
    }
  }
}
