/**
 * AUTO-GENERATED by scripts/generate-wrappers.mjs - DO NOT EDIT.
 * Regenerate: pnpm --filter @svgrid/grid-wc generate:wrappers
 *
 * Angular wrapper. Binds Angular @Input / @Output straight onto the custom element, which IS this component's host.
 */
/* eslint-disable @typescript-eslint/no-explicit-any */
import {
  Component,
  ElementRef,
  EventEmitter,
  Input,
  OnChanges,
  OnDestroy,
  OnInit,
  Output,
  SimpleChanges,
} from '@angular/core'
import '@svgrid/grid-wc'

const PROP_NAMES: string[] = ["data","columns","board","scheduler","chart","pivot","pivotMode","contextMenu","selectionBar","features","sortable","filterable","editable","treeData","groupable","groupBy","expanded","groupFooters","grandTotalRow","groupDisplayMode","autoGroupColumnHeader","autoGroupColumnWidth","pageable","loading","loadingOverlay","loadingSkeletonRows","error","emptyMessage","localization","showGlobalFilter","showColumnFilters","filterMode","showGroupingControls","showRowSelection","showPagination","pageSize","pageSizeOptions","paginationPosition","externalPagination","rowCount","pageIndex","virtualization","rowHeight","autoRowHeight","rowResize","headerHeight","overscan","containerHeight","columnVirtualization","columnOverscan","columnWidth","initialColumnPinning","fitColumns","columnResize","responsive","showFilterMenu","showFilterRow","enableCellSelection","moveCells","enableRowHover","copyHeadersToClipboard","processCellForClipboard","enableInlineEditing","fullRowEditing","enableRowSummaries","summary","statusBar","toolPanel","charting","columnMenuTabs","toolPanelDefaultOpen","toolPanelDefaultTab","selectionMode","showRowNumbers","zebraRows","rowNumberWidth","externalSort","initialSorting","initialAdvancedFilter","externalFilter","getRowId","rowClass","notes","editableComments","conditionalFormats","conditionalStatScope","isDetailRow","serverGroup","serverFilterValues","pinnedTopRows","pinnedBottomRows","enableColumnReorder","columnOrder","inferColumnTypes","rowDragManaged","rowDragGroup","alignedGridGroup","filterLocale"]
const EVENT_NAMES: string[] = ["pivotmodechange","expandedchange","paginationchange","apiready","rowselectionchange","cellselectionchange","sortingchange","advancedfilterchange","filterschange","notechange","cellvaluechange","activecellchange","cellclick","rowclick","celldoubleclick","rowdoubleclick","scrollbottomreached","columnorderchange","rowdragend","selectionchange"]

/**
 * SvGrid as an Angular component.
 *
 * The selector is the custom element's own tag, and the component has NO
 * template: its host element IS the `<sv-grid>` the browser upgrades. So a
 * consumer writes the same tag they would write in plain HTML, and there is no
 * second wrapper element in the DOM.
 *
 * A wrapper with its own tag (`<svgrid-grid>`) rendering `<sv-grid>` inside
 * it was the first shape. It works, but it puts a redundant element in every
 * consumer's DOM and gives the same grid two different names depending on which
 * framework you came from.
 *
 * Matching `sv-grid-shadow` too means the shadow-root variant is the same
 * choice it is everywhere else - the tag you write - rather than an input that
 * only this framework has.
 */
@Component({
  selector: 'sv-grid, sv-grid-shadow',
  standalone: true,
  template: '',
})
export class SvGridComponent implements OnInit, OnChanges, OnDestroy {
  @Input() data?: readonly unknown[]
  @Input() columns?: readonly unknown[]
  @Input() board?: unknown
  @Input() scheduler?: unknown
  @Input() chart?: unknown
  @Input() pivot?: unknown
  @Input() pivotMode?: boolean
  @Input() contextMenu?: boolean
  @Input() selectionBar?: boolean
  @Input() features?: unknown
  @Input() sortable?: boolean
  @Input() filterable?: boolean
  @Input() editable?: boolean
  @Input() treeData?: unknown
  @Input() groupable?: boolean
  @Input() groupBy?: readonly unknown[]
  @Input() expanded?: unknown
  @Input() groupFooters?: boolean
  @Input() grandTotalRow?: boolean
  @Input() groupDisplayMode?: string
  @Input() autoGroupColumnHeader?: string
  @Input() autoGroupColumnWidth?: number
  @Input() pageable?: boolean
  @Input() loading?: boolean
  @Input() loadingOverlay?: boolean
  @Input() loadingSkeletonRows?: number
  @Input() error?: string | null
  @Input() emptyMessage?: string
  @Input() localization?: unknown
  @Input() showGlobalFilter?: boolean
  @Input() showColumnFilters?: boolean
  @Input() filterMode?: "row" | "menu" | "global" | "none"
  @Input() showGroupingControls?: boolean
  @Input() showRowSelection?: boolean
  @Input() showPagination?: boolean
  @Input() pageSize?: number
  @Input() pageSizeOptions?: readonly unknown[]
  @Input() paginationPosition?: "top" | "bottom" | "both"
  @Input() externalPagination?: boolean
  @Input() rowCount?: number
  @Input() pageIndex?: number
  @Input() virtualization?: boolean
  @Input() rowHeight?: number
  @Input() autoRowHeight?: boolean
  @Input() rowResize?: boolean
  @Input() headerHeight?: number
  @Input() overscan?: number
  @Input() containerHeight?: string
  @Input() columnVirtualization?: boolean
  @Input() columnOverscan?: number
  @Input() columnWidth?: number
  @Input() initialColumnPinning?: unknown
  @Input() fitColumns?: boolean
  @Input() columnResize?: boolean
  @Input() responsive?: boolean
  @Input() showFilterMenu?: boolean
  @Input() showFilterRow?: boolean
  @Input() enableCellSelection?: boolean
  @Input() moveCells?: boolean
  @Input() enableRowHover?: boolean
  @Input() copyHeadersToClipboard?: boolean
  @Input() processCellForClipboard?: unknown
  @Input() enableInlineEditing?: boolean
  @Input() fullRowEditing?: boolean
  @Input() enableRowSummaries?: boolean
  @Input() summary?: boolean
  @Input() statusBar?: boolean
  @Input() toolPanel?: boolean
  @Input() charting?: boolean
  @Input() columnMenuTabs?: boolean
  @Input() toolPanelDefaultOpen?: boolean
  @Input() toolPanelDefaultTab?: "columns" | "filters"
  @Input() selectionMode?: "row" | "cell" | "both" | "none"
  @Input() showRowNumbers?: boolean
  @Input() zebraRows?: boolean
  @Input() rowNumberWidth?: number
  @Input() externalSort?: boolean
  @Input() initialSorting?: readonly unknown[]
  @Input() initialAdvancedFilter?: unknown
  @Input() externalFilter?: boolean
  @Input() getRowId?: unknown
  @Input() rowClass?: unknown
  @Input() notes?: unknown
  @Input() editableComments?: boolean
  @Input() conditionalFormats?: readonly unknown[]
  @Input() conditionalStatScope?: "filtered" | "visible" | "all"
  @Input() isDetailRow?: unknown
  @Input() serverGroup?: unknown
  @Input() serverFilterValues?: unknown
  @Input() pinnedTopRows?: readonly unknown[]
  @Input() pinnedBottomRows?: readonly unknown[]
  @Input() enableColumnReorder?: boolean
  @Input() columnOrder?: readonly unknown[]
  @Input() inferColumnTypes?: boolean
  @Input() rowDragManaged?: boolean
  @Input() rowDragGroup?: string
  @Input() alignedGridGroup?: string
  @Input() filterLocale?: string

  @Output() pivotmodechange = new EventEmitter<unknown>()
  @Output() expandedchange = new EventEmitter<unknown>()
  @Output() paginationchange = new EventEmitter<unknown>()
  @Output() apiready = new EventEmitter<unknown>()
  @Output() rowselectionchange = new EventEmitter<unknown>()
  @Output() cellselectionchange = new EventEmitter<unknown>()
  @Output() sortingchange = new EventEmitter<unknown>()
  @Output() advancedfilterchange = new EventEmitter<unknown>()
  @Output() filterschange = new EventEmitter<unknown>()
  @Output() notechange = new EventEmitter<unknown>()
  @Output() cellvaluechange = new EventEmitter<unknown>()
  @Output() activecellchange = new EventEmitter<unknown>()
  @Output() cellclick = new EventEmitter<unknown>()
  @Output() rowclick = new EventEmitter<unknown>()
  @Output() celldoubleclick = new EventEmitter<unknown>()
  @Output() rowdoubleclick = new EventEmitter<unknown>()
  @Output() scrollbottomreached = new EventEmitter<unknown>()
  @Output() columnorderchange = new EventEmitter<unknown>()
  @Output() rowdragend = new EventEmitter<unknown>()
  @Output() selectionchange = new EventEmitter<unknown>()

  private listeners: Array<[string, EventListener]> = []

  constructor(private readonly elementRef: ElementRef<HTMLElement>) {}

  ngOnInit(): void {
    const el = this.elementRef.nativeElement

    // The shadow element is a separate bundle. Loading it lazily means the tag
    // is not upgraded yet, and properties assigned to an un-upgraded element
    // are shadowed by the class fields the upgrade installs - so re-sync once
    // the definition lands.
    if (el.tagName === 'SV-GRID-SHADOW')
      void import('@svgrid/grid-wc/shadow').then(() => this.sync(PROP_NAMES))

    for (const name of EVENT_NAMES) {
      const listener: EventListener = (e) =>
        (this as any)[name]?.emit((e as CustomEvent).detail)
      el.addEventListener(name, listener)
      this.listeners.push([name, listener])
    }

    this.sync(PROP_NAMES)

    // `apiready` fires once, during the element's own mount, so a listener
    // bound here can miss it. The element parks the handle for that reason.
    const api = (el as HTMLElement & { api?: unknown }).api
    if (api != null) this.apiready.emit(api)
  }

  ngOnChanges(changes: SimpleChanges): void {
    this.sync(Object.keys(changes).filter((k) => PROP_NAMES.includes(k)))
  }

  ngOnDestroy(): void {
    const el = this.elementRef.nativeElement
    for (const [name, listener] of this.listeners) el.removeEventListener(name, listener)
    this.listeners = []
  }

  /** Assign as DOM PROPERTIES - an attribute is a string, and most of these are not. */
  private sync(names: string[]): void {
    const el = this.elementRef.nativeElement as HTMLElement & Record<string, unknown>
    for (const name of names) {
      const value = (this as any)[name]
      if (value !== undefined) el[name] = value
    }
  }

  /** The grid api, once it is ready. */
  get api(): unknown {
    return (this.elementRef.nativeElement as HTMLElement & { api?: unknown }).api ?? null
  }
}
